# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:/LineMinecraftLauncherProject/Refactor/Line/Interface/Interface/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(836, 470)
        self.Navigation = NavigationInterface(Form)
        self.Navigation.setGeometry(QtCore.QRect(0, 10, 48, 461))
        self.Navigation.setObjectName("Navigation")
        self.poper = PopUpAniStackedWidget(Form)
        self.poper.setGeometry(QtCore.QRect(60, 20, 781, 441))
        self.poper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.poper.setObjectName("poper")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.SubtitleLabel_3 = SubtitleLabel(self.home)
        self.SubtitleLabel_3.setGeometry(QtCore.QRect(0, 10, 241, 28))
        self.SubtitleLabel_3.setObjectName("SubtitleLabel_3")
        self.BodyLabel = BodyLabel(self.home)
        self.BodyLabel.setGeometry(QtCore.QRect(0, 40, 711, 19))
        self.BodyLabel.setText("")
        self.BodyLabel.setObjectName("BodyLabel")
        self.poper.addWidget(self.home)
        self.launch = QtWidgets.QWidget()
        self.launch.setObjectName("launch")
        self.SubtitleLabel_2 = SubtitleLabel(self.launch)
        self.SubtitleLabel_2.setGeometry(QtCore.QRect(20, 10, 119, 28))
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.MemoryAdjuster = Slider(self.launch)
        self.MemoryAdjuster.setGeometry(QtCore.QRect(30, 390, 291, 31))
        self.MemoryAdjuster.setStyleSheet("QSlider:horizontal {\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 4px;\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #009faa;\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    border: 1px solid rgb(222, 222, 222);\n"
"    width: 20px;\n"
"    min-height: 24px;\n"
"    margin: -9px 0;\n"
"    border-radius: 11px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.48 #009faa,\n"
"        stop:0.55 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.55 #009faa,\n"
"        stop:0.65 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.4 #009faa,\n"
"        stop:0.5 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::groove:horizontal:disabled {\n"
"    background-color: rgba(0, 0, 0, 75);\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"    background-color: #808080;\n"
"    border: 5px solid #cccccc;\n"
"}\n"
"\n"
"\n"
"QSlider:vertical {\n"
"    min-width: 24px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    width: 4px;\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #009faa;\n"
"    width: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    border: 1px solid rgb(222, 222, 222);\n"
"    height: 20px;\n"
"    min-width: 24px;\n"
"    margin: 0 -9px;\n"
"    border-radius: 11px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.48 #009faa,\n"
"        stop:0.55 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.55 #009faa,\n"
"        stop:0.65 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.4 #009faa,\n"
"        stop:0.5 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::groove:vertical:disabled {\n"
"    background-color: rgba(0, 0, 0, 75);\n"
"}\n"
"\n"
"QSlider::handle:vertical:disabled {\n"
"    background-color: #808080;\n"
"    border: 5px solid #cccccc;\n"
"}\n"
"")
        self.MemoryAdjuster.setOrientation(QtCore.Qt.Horizontal)
        self.MemoryAdjuster.setObjectName("MemoryAdjuster")
        self.CaptionLabel = CaptionLabel(self.launch)
        self.CaptionLabel.setGeometry(QtCore.QRect(40, 370, 70, 15))
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.CaptionLabel_2 = CaptionLabel(self.launch)
        self.CaptionLabel_2.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.CaptionLabel_5 = CaptionLabel(self.launch)
        self.CaptionLabel_5.setGeometry(QtCore.QRect(30, 200, 151, 16))
        self.CaptionLabel_5.setObjectName("CaptionLabel_5")
        self.ManageMinecraft = PushButton(self.launch)
        self.ManageMinecraft.setGeometry(QtCore.QRect(20, 280, 101, 32))
        self.ManageMinecraft.setObjectName("ManageMinecraft")
        self.AddMinecraftDirectory = PushButton(self.launch)
        self.AddMinecraftDirectory.setGeometry(QtCore.QRect(20, 320, 102, 32))
        self.AddMinecraftDirectory.setObjectName("AddMinecraftDirectory")
        self.LaunchingAccountsSelector = EditableComboBox(self.launch)
        self.LaunchingAccountsSelector.setGeometry(QtCore.QRect(20, 80, 181, 33))
        self.LaunchingAccountsSelector.setObjectName("LaunchingAccountsSelector")
        self.MemorySizeDisplay = CaptionLabel(self.launch)
        self.MemorySizeDisplay.setGeometry(QtCore.QRect(100, 370, 70, 15))
        self.MemorySizeDisplay.setText("")
        self.MemorySizeDisplay.setObjectName("MemorySizeDisplay")
        self.Launch = PrimarySplitPushButton(self.launch)
        self.Launch.setGeometry(QtCore.QRect(590, 380, 141, 33))
        self.Launch.setObjectName("Launch")
        self.LoginTypeSwitcher = ToggleButton(self.launch)
        self.LoginTypeSwitcher.setGeometry(QtCore.QRect(20, 130, 113, 32))
        self.LoginTypeSwitcher.setObjectName("LoginTypeSwitcher")
        self.MinecraftPathSelector = EditableComboBox(self.launch)
        self.MinecraftPathSelector.setGeometry(QtCore.QRect(20, 230, 181, 33))
        self.MinecraftPathSelector.setObjectName("MinecraftPathSelector")
        self.poper.addWidget(self.launch)
        self.account = QtWidgets.QWidget()
        self.account.setObjectName("account")
        self.SubtitleLabel = SubtitleLabel(self.account)
        self.SubtitleLabel.setGeometry(QtCore.QRect(10, 10, 119, 28))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.Login = PushButton(self.account)
        self.Login.setGeometry(QtCore.QRect(10, 50, 102, 32))
        self.Login.setObjectName("Login")
        self.Manage = PushButton(self.account)
        self.Manage.setGeometry(QtCore.QRect(130, 50, 102, 32))
        self.Manage.setObjectName("Manage")
        self.poper.addWidget(self.account)
        self.terminal = QtWidgets.QWidget()
        self.terminal.setObjectName("terminal")
        self.SubtitleLabel_4 = SubtitleLabel(self.terminal)
        self.SubtitleLabel_4.setGeometry(QtCore.QRect(20, 10, 119, 28))
        self.SubtitleLabel_4.setObjectName("SubtitleLabel_4")
        self.poper.addWidget(self.terminal)
        self.download = QtWidgets.QWidget()
        self.download.setObjectName("download")
        self.SubtitleLabel_5 = SubtitleLabel(self.download)
        self.SubtitleLabel_5.setGeometry(QtCore.QRect(20, 10, 161, 28))
        self.SubtitleLabel_5.setObjectName("SubtitleLabel_5")
        self.Download = PushButton(self.download)
        self.Download.setGeometry(QtCore.QRect(20, 50, 102, 32))
        self.Download.setObjectName("Download")
        self.ManageDownloadedGame = PushButton(self.download)
        self.ManageDownloadedGame.setGeometry(QtCore.QRect(130, 50, 102, 32))
        self.ManageDownloadedGame.setObjectName("ManageDownloadedGame")
        self.CurseForgeModDownload = PushButton(self.download)
        self.CurseForgeModDownload.setGeometry(QtCore.QRect(30, 240, 102, 32))
        self.CurseForgeModDownload.setObjectName("CurseForgeModDownload")
        self.BodyLabel_2 = BodyLabel(self.download)
        self.BodyLabel_2.setGeometry(QtCore.QRect(40, 220, 111, 19))
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.CurseForgePackagesDownload = PushButton(self.download)
        self.CurseForgePackagesDownload.setGeometry(QtCore.QRect(150, 240, 102, 32))
        self.CurseForgePackagesDownload.setObjectName("CurseForgePackagesDownload")
        self.poper.addWidget(self.download)
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.SubtitleLabel_6 = SubtitleLabel(self.settings)
        self.SubtitleLabel_6.setGeometry(QtCore.QRect(10, 10, 119, 28))
        self.SubtitleLabel_6.setObjectName("SubtitleLabel_6")
        self.SmoothScrollArea = SmoothScrollArea(self.settings)
        self.SmoothScrollArea.setGeometry(QtCore.QRect(10, 50, 731, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SmoothScrollArea.sizePolicy().hasHeightForWidth())
        self.SmoothScrollArea.setSizePolicy(sizePolicy)
        self.SmoothScrollArea.setMinimumSize(QtCore.QSize(0, 200))
        self.SmoothScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SmoothScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SmoothScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SmoothScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 718, 432))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DownloadSourceCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DownloadSourceCard.sizePolicy().hasHeightForWidth())
        self.DownloadSourceCard.setSizePolicy(sizePolicy)
        self.DownloadSourceCard.setMinimumSize(QtCore.QSize(700, 0))
        self.DownloadSourceCard.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DownloadSourceCard.setLineWidth(10)
        self.DownloadSourceCard.setObjectName("DownloadSourceCard")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.DownloadSourceCard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BodyLabel_7 = BodyLabel(self.DownloadSourceCard)
        self.BodyLabel_7.setObjectName("BodyLabel_7")
        self.verticalLayout.addWidget(self.BodyLabel_7)
        self.DownloadSourceSelector = ComboBox(self.DownloadSourceCard)
        self.DownloadSourceSelector.setObjectName("DownloadSourceSelector")
        self.verticalLayout.addWidget(self.DownloadSourceSelector)
        self.verticalLayout_2.addWidget(self.DownloadSourceCard)
        self.LanguageCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LanguageCard.sizePolicy().hasHeightForWidth())
        self.LanguageCard.setSizePolicy(sizePolicy)
        self.LanguageCard.setMinimumSize(QtCore.QSize(0, 100))
        self.LanguageCard.setObjectName("LanguageCard")
        self.BodyLabel_12 = BodyLabel(self.LanguageCard)
        self.BodyLabel_12.setGeometry(QtCore.QRect(10, 10, 63, 19))
        self.BodyLabel_12.setObjectName("BodyLabel_12")
        self.LanguageSelector = ComboBox(self.LanguageCard)
        self.LanguageSelector.setGeometry(QtCore.QRect(10, 50, 671, 32))
        self.LanguageSelector.setObjectName("LanguageSelector")
        self.verticalLayout_2.addWidget(self.LanguageCard)
        self.JavaCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JavaCard.sizePolicy().hasHeightForWidth())
        self.JavaCard.setSizePolicy(sizePolicy)
        self.JavaCard.setMinimumSize(QtCore.QSize(0, 150))
        self.JavaCard.setObjectName("JavaCard")
        self.BodyLabel_8 = BodyLabel(self.JavaCard)
        self.BodyLabel_8.setGeometry(QtCore.QRect(10, 10, 63, 19))
        self.BodyLabel_8.setObjectName("BodyLabel_8")
        self.BodyLabel_9 = BodyLabel(self.JavaCard)
        self.BodyLabel_9.setGeometry(QtCore.QRect(20, 80, 141, 19))
        self.BodyLabel_9.setObjectName("BodyLabel_9")
        self.JavaSelectionPlan = ComboBox(self.JavaCard)
        self.JavaSelectionPlan.setGeometry(QtCore.QRect(20, 110, 201, 32))
        self.JavaSelectionPlan.setObjectName("JavaSelectionPlan")
        self.AddJavaManually = PushButton(self.JavaCard)
        self.AddJavaManually.setGeometry(QtCore.QRect(230, 110, 102, 32))
        self.AddJavaManually.setObjectName("AddJavaManually")
        self.BodyLabel_10 = BodyLabel(self.JavaCard)
        self.BodyLabel_10.setGeometry(QtCore.QRect(360, 80, 301, 19))
        self.BodyLabel_10.setObjectName("BodyLabel_10")
        self.JavaForce = ComboBox(self.JavaCard)
        self.JavaForce.setGeometry(QtCore.QRect(360, 110, 301, 32))
        self.JavaForce.setObjectName("JavaForce")
        self.SearchJava = TransparentPushButton(self.JavaCard)
        self.SearchJava.setGeometry(QtCore.QRect(20, 50, 101, 30))
        self.SearchJava.setProperty("hasIcon", True)
        self.SearchJava.setObjectName("SearchJava")
        self.verticalLayout_2.addWidget(self.JavaCard)
        self.LauncherVisiableCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LauncherVisiableCard.sizePolicy().hasHeightForWidth())
        self.LauncherVisiableCard.setSizePolicy(sizePolicy)
        self.LauncherVisiableCard.setMinimumSize(QtCore.QSize(0, 70))
        self.LauncherVisiableCard.setObjectName("LauncherVisiableCard")
        self.BodyLabel_11 = BodyLabel(self.LauncherVisiableCard)
        self.BodyLabel_11.setGeometry(QtCore.QRect(10, 0, 131, 19))
        self.BodyLabel_11.setObjectName("BodyLabel_11")
        self.LauncherVisiableSelector = ComboBox(self.LauncherVisiableCard)
        self.LauncherVisiableSelector.setGeometry(QtCore.QRect(10, 30, 671, 32))
        self.LauncherVisiableSelector.setObjectName("LauncherVisiableSelector")
        self.verticalLayout_2.addWidget(self.LauncherVisiableCard)
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.poper.addWidget(self.settings)
        self.LoginSub = QtWidgets.QWidget()
        self.LoginSub.setObjectName("LoginSub")
        self.SubtitleLabel_7 = SubtitleLabel(self.LoginSub)
        self.SubtitleLabel_7.setGeometry(QtCore.QRect(10, 10, 171, 28))
        self.SubtitleLabel_7.setObjectName("SubtitleLabel_7")
        self.MicrosoftLogin = PushButton(self.LoginSub)
        self.MicrosoftLogin.setGeometry(QtCore.QRect(10, 70, 102, 32))
        self.MicrosoftLogin.setObjectName("MicrosoftLogin")
        self.OfflinedLogin = PushButton(self.LoginSub)
        self.OfflinedLogin.setGeometry(QtCore.QRect(140, 70, 102, 32))
        self.OfflinedLogin.setObjectName("OfflinedLogin")
        self.poper.addWidget(self.LoginSub)
        self.LoginSubPageMic = QtWidgets.QWidget()
        self.LoginSubPageMic.setObjectName("LoginSubPageMic")
        self.SubtitleLabel_8 = SubtitleLabel(self.LoginSubPageMic)
        self.SubtitleLabel_8.setGeometry(QtCore.QRect(10, 10, 201, 28))
        self.SubtitleLabel_8.setObjectName("SubtitleLabel_8")
        self.AddAccount = PushButton(self.LoginSubPageMic)
        self.AddAccount.setGeometry(QtCore.QRect(10, 100, 102, 32))
        self.AddAccount.setObjectName("AddAccount")
        self.poper.addWidget(self.LoginSubPageMic)
        self.LoginSubPageOffline = QtWidgets.QWidget()
        self.LoginSubPageOffline.setObjectName("LoginSubPageOffline")
        self.SubtitleLabel_9 = SubtitleLabel(self.LoginSubPageOffline)
        self.SubtitleLabel_9.setGeometry(QtCore.QRect(20, 10, 191, 28))
        self.SubtitleLabel_9.setObjectName("SubtitleLabel_9")
        self.CaptionLabel_4 = CaptionLabel(self.LoginSubPageOffline)
        self.CaptionLabel_4.setGeometry(QtCore.QRect(30, 70, 70, 15))
        self.CaptionLabel_4.setObjectName("CaptionLabel_4")
        self.Username = LineEdit(self.LoginSubPageOffline)
        self.Username.setGeometry(QtCore.QRect(30, 100, 391, 33))
        self.Username.setObjectName("Username")
        self.ConfirmUsername = PushButton(self.LoginSubPageOffline)
        self.ConfirmUsername.setGeometry(QtCore.QRect(30, 150, 102, 32))
        self.ConfirmUsername.setObjectName("ConfirmUsername")
        self.ClearUsername = PushButton(self.LoginSubPageOffline)
        self.ClearUsername.setGeometry(QtCore.QRect(320, 150, 102, 32))
        self.ClearUsername.setObjectName("ClearUsername")
        self.poper.addWidget(self.LoginSubPageOffline)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.VersionsView = ListWidget(self.page)
        self.VersionsView.setGeometry(QtCore.QRect(0, 0, 741, 361))
        self.VersionsView.setObjectName("VersionsView")
        self.ShowOldVersions = CheckBox(self.page)
        self.ShowOldVersions.setGeometry(QtCore.QRect(440, 380, 92, 22))
        self.ShowOldVersions.setObjectName("ShowOldVersions")
        self.ShowSnapshotVersions = CheckBox(self.page)
        self.ShowSnapshotVersions.setGeometry(QtCore.QRect(560, 380, 92, 22))
        self.ShowSnapshotVersions.setObjectName("ShowSnapshotVersions")
        self.poper.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.SubtitleLabel_10 = SubtitleLabel(self.page_2)
        self.SubtitleLabel_10.setGeometry(QtCore.QRect(10, 10, 119, 28))
        self.SubtitleLabel_10.setObjectName("SubtitleLabel_10")
        self.versionDisplay = BodyLabel(self.page_2)
        self.versionDisplay.setGeometry(QtCore.QRect(20, 60, 371, 19))
        self.versionDisplay.setText("")
        self.versionDisplay.setObjectName("versionDisplay")
        self.subProgramSelect = SmoothScrollArea(self.page_2)
        self.subProgramSelect.setGeometry(QtCore.QRect(10, 100, 691, 271))
        self.subProgramSelect.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.subProgramSelect.setLineWidth(1)
        self.subProgramSelect.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.subProgramSelect.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.subProgramSelect.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.subProgramSelect.setWidgetResizable(True)
        self.subProgramSelect.setObjectName("subProgramSelect")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 672, 269))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.ForgeSelector = ComboBox(self.scrollAreaWidgetContents_2)
        self.ForgeSelector.setGeometry(QtCore.QRect(0, 20, 671, 32))
        self.ForgeSelector.setObjectName("ForgeSelector")
        self.BodyLabel_3 = BodyLabel(self.scrollAreaWidgetContents_2)
        self.BodyLabel_3.setGeometry(QtCore.QRect(10, 0, 63, 19))
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.BodyLabel_4 = BodyLabel(self.scrollAreaWidgetContents_2)
        self.BodyLabel_4.setGeometry(QtCore.QRect(10, 60, 63, 19))
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.FabricSelector = ComboBox(self.scrollAreaWidgetContents_2)
        self.FabricSelector.setGeometry(QtCore.QRect(0, 90, 671, 32))
        self.FabricSelector.setObjectName("FabricSelector")
        self.BodyLabel_5 = BodyLabel(self.scrollAreaWidgetContents_2)
        self.BodyLabel_5.setGeometry(QtCore.QRect(10, 130, 63, 19))
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.OptifineSelector = ComboBox(self.scrollAreaWidgetContents_2)
        self.OptifineSelector.setGeometry(QtCore.QRect(10, 160, 661, 32))
        self.OptifineSelector.setObjectName("OptifineSelector")
        self.BodyLabel_6 = BodyLabel(self.scrollAreaWidgetContents_2)
        self.BodyLabel_6.setGeometry(QtCore.QRect(10, 200, 111, 19))
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.OptiFabricSelector = ComboBox(self.scrollAreaWidgetContents_2)
        self.OptiFabricSelector.setGeometry(QtCore.QRect(10, 230, 661, 32))
        self.OptiFabricSelector.setObjectName("OptiFabricSelector")
        self.subProgramSelect.setWidget(self.scrollAreaWidgetContents_2)
        self.ConfirmDownload = PushButton(self.page_2)
        self.ConfirmDownload.setGeometry(QtCore.QRect(600, 380, 102, 32))
        self.ConfirmDownload.setObjectName("ConfirmDownload")
        self.ClearOption = PushButton(self.page_2)
        self.ClearOption.setGeometry(QtCore.QRect(480, 380, 102, 32))
        self.ClearOption.setObjectName("ClearOption")
        self.ReturnPreviousStep = PushButton(self.page_2)
        self.ReturnPreviousStep.setGeometry(QtCore.QRect(360, 380, 102, 32))
        self.ReturnPreviousStep.setObjectName("ReturnPreviousStep")
        self.poper.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.SubtitleLabel_11 = SubtitleLabel(self.page_3)
        self.SubtitleLabel_11.setGeometry(QtCore.QRect(10, 10, 211, 28))
        self.SubtitleLabel_11.setObjectName("SubtitleLabel_11")
        self.MinecraftDirectoriesManagementView = ListWidget(self.page_3)
        self.MinecraftDirectoriesManagementView.setGeometry(QtCore.QRect(10, 40, 731, 381))
        self.MinecraftDirectoriesManagementView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: transparent;\n"
"    outline: none;\n"
"    border: none;\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    font: 75 italic 12pt \"MS Sans Serif\";\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(108, 95, 154);\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"ListView::indicator:hover,\n"
"ListWidget::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"ListView::indicator:pressed,\n"
"ListWidget::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"ListView::indicator:checke,\n"
"ListWidget::indicator:checked,\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"ListView::indicator:checked,\n"
"ListWidget::indicator:checked {\n"
"    image: url(:/qfluentwidgets/images/check_box/Accept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    image: url(:/qfluentwidgets/images/check_box/PartialAccept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:checked:hove,\n"
"ListWidget::indicator:checked:hover,\n"
"ListView::indicator:indeterminate:hover,\n"
"ListWidget::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"ListView::indicator:checked:presse,\n"
"ListWidget::indicator:checked:pressed,\n"
"ListView::indicator:indeterminate:pressed,\n"
"ListWidget::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"ListView::indicator:disabled,\n"
"ListWidget::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"ListView::indicator:checked:disable,\n"
"ListWidget::indicator:checked:disabled,\n"
"ListView::indicator:indeterminate:disabled,\n"
"ListWidget::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.MinecraftDirectoriesManagementView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MinecraftDirectoriesManagementView.setObjectName("MinecraftDirectoriesManagementView")
        self.poper.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.SubtitleLabel_12 = SubtitleLabel(self.page_4)
        self.SubtitleLabel_12.setGeometry(QtCore.QRect(20, 10, 119, 28))
        self.SubtitleLabel_12.setObjectName("SubtitleLabel_12")
        self.MinecraftDirectoryManagement = BodyLabel(self.page_4)
        self.MinecraftDirectoryManagement.setGeometry(QtCore.QRect(20, 70, 741, 31))
        self.MinecraftDirectoryManagement.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"border-color:rgb(108, 95, 154);\n"
"border-radius: 10px\n"
"")
        self.MinecraftDirectoryManagement.setObjectName("MinecraftDirectoryManagement")
        self.OpenManagedMinecraftDircetory = PushButton(self.page_4)
        self.OpenManagedMinecraftDircetory.setGeometry(QtCore.QRect(30, 110, 102, 32))
        self.OpenManagedMinecraftDircetory.setObjectName("OpenManagedMinecraftDircetory")
        self.CurrentMinecrafts = BodyLabel(self.page_4)
        self.CurrentMinecrafts.setGeometry(QtCore.QRect(20, 230, 741, 31))
        self.CurrentMinecrafts.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"border-color:rgb(108, 95, 154);\n"
"border-radius: 10px\n"
"")
        self.CurrentMinecrafts.setObjectName("CurrentMinecrafts")
        self.ManagementCustomName = BodyLabel(self.page_4)
        self.ManagementCustomName.setGeometry(QtCore.QRect(20, 150, 741, 31))
        self.ManagementCustomName.setStyleSheet("border-style: solid;\n"
"border-width: 3px;\n"
"border-color:rgb(108, 95, 154);\n"
"border-radius: 10px\n"
"")
        self.ManagementCustomName.setObjectName("ManagementCustomName")
        self.RenameMinecraftDirectory = PushButton(self.page_4)
        self.RenameMinecraftDirectory.setGeometry(QtCore.QRect(30, 190, 102, 32))
        self.RenameMinecraftDirectory.setObjectName("RenameMinecraftDirectory")
        self.CurrentMinecraftsView = ListWidget(self.page_4)
        self.CurrentMinecraftsView.setGeometry(QtCore.QRect(30, 290, 731, 111))
        self.CurrentMinecraftsView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: transparent;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    font: 75 italic 12pt \"MS Sans Serif\";\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(108, 95, 154);\n"
"    background: transparent;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"ListView::indicator:hover,\n"
"ListWidget::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"ListView::indicator:pressed,\n"
"ListWidget::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"ListView::indicator:checke,\n"
"ListWidget::indicator:checked,\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"ListView::indicator:checked,\n"
"ListWidget::indicator:checked {\n"
"    image: url(:/qfluentwidgets/images/check_box/Accept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    image: url(:/qfluentwidgets/images/check_box/PartialAccept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:checked:hove,\n"
"ListWidget::indicator:checked:hover,\n"
"ListView::indicator:indeterminate:hover,\n"
"ListWidget::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"ListView::indicator:checked:presse,\n"
"ListWidget::indicator:checked:pressed,\n"
"ListView::indicator:indeterminate:pressed,\n"
"ListWidget::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"ListView::indicator:disabled,\n"
"ListWidget::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"ListView::indicator:checked:disable,\n"
"ListWidget::indicator:checked:disabled,\n"
"ListView::indicator:indeterminate:disabled,\n"
"ListWidget::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CurrentMinecraftsView.setObjectName("CurrentMinecraftsView")
        self.DelManagedDirectory = PushButton(self.page_4)
        self.DelManagedDirectory.setGeometry(QtCore.QRect(140, 110, 102, 32))
        self.DelManagedDirectory.setStyleSheet("PushButton, ToolButton, ToggleButton, ToggleToolButton {\n"
"    color: red;\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"ToolButton {\n"
"    padding: 5px 9px 6px 8px;\n"
"}\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"DropDownToolButton, PrimaryDropDownToolButton {\n"
"    padding: 5px 31px 6px 8px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"PushButton:pressed, ToolButton:pressed, ToggleButton:pressed, ToggleToolButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"PushButton:disabled, ToolButton:disabled, ToggleButton:disabled, ToggleToolButton:disabled {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"\n"
"\n"
"PrimaryPushButton,\n"
"PrimaryToolButton,\n"
"ToggleButton:checked,\n"
"ToggleToolButton:checked {\n"
"    color: white;\n"
"    background-color: #009faa;\n"
"    border: 1px solid #00a7b3;\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"PrimaryPushButton:hover,\n"
"PrimaryToolButton:hover,\n"
"ToggleButton:checked:hover,\n"
"ToggleToolButton:checked:hover {\n"
"    background-color: #00a7b3;\n"
"    border: 1px solid #2daab3;\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"PrimaryPushButton:pressed,\n"
"PrimaryToolButton:pressed,\n"
"ToggleButton:checked:pressed,\n"
"ToggleToolButton:checked:pressed {\n"
"    color: rgba(255, 255, 255, 0.63);\n"
"    background-color: #3eabb3;\n"
"    border: 1px solid #3eabb3;\n"
"}\n"
"\n"
"PrimaryPushButton:disabled,\n"
"PrimaryToolButton:disabled,\n"
"ToggleButton:checked:disabled,\n"
"ToggleToolButton:checked:disabled {\n"
"    color: rgba(255, 255, 255, 0.9);\n"
"    background-color: rgb(205, 205, 205);\n"
"    border: 1px solid rgb(205, 205, 205);\n"
"}\n"
"\n"
"SplitDropButton,\n"
"PrimarySplitDropButton {\n"
"    border-left: none;\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"}\n"
"\n"
"#splitPushButton,\n"
"#splitToolButton,\n"
"#primarySplitPushButton,\n"
"#primarySplitToolButton {\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"}\n"
"\n"
"#splitPushButton:pressed,\n"
"#splitToolButton:pressed,\n"
"SplitDropButton:pressed {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"}\n"
"\n"
"PrimarySplitDropButton:pressed {\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"#primarySplitPushButton, #primarySplitToolButton {\n"
"    border-right: 1px solid #3eabb3;\n"
"}\n"
"\n"
"#primarySplitPushButton:pressed, #primarySplitToolButton:pressed {\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"HyperlinkButton {\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 6px 12px 6px 12px;\n"
"    color: #009faa;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"HyperlinkButton[hasIcon=false] {\n"
"    padding: 6px 12px 6px 12px;\n"
"}\n"
"\n"
"HyperlinkButton[hasIcon=true] {\n"
"    padding: 6px 12px 6px 36px;\n"
"}\n"
"\n"
"HyperlinkButton:hover {\n"
"    color: #009faa;\n"
"    background-color: rgba(0, 0, 0, 10);\n"
"    border: none;\n"
"}\n"
"\n"
"HyperlinkButton:pressed {\n"
"    color: #009faa;\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"HyperlinkButton:disabled {\n"
"    color: rgba(0, 0, 0, 0.43);\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"RadioButton {\n"
"    min-height: 24px;\n"
"    max-height: 24px;\n"
"    background-color: transparent;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    color: black;\n"
"}\n"
"\n"
"RadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 11px;\n"
"    border: 2px solid #999999;\n"
"    background-color: rgba(0, 0, 0, 5);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"RadioButton::indicator:hover {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"RadioButton::indicator:pressed {\n"
"    border: 2px solid #bbbbbb;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 rgb(225, 224, 223),\n"
"            stop:1 rgb(225, 224, 223));\n"
"}\n"
"\n"
"RadioButton::indicator:checked {\n"
"    height: 22px;\n"
"    width: 22px;\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton::indicator:checked:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.6 rgb(255, 255, 255),\n"
"            stop:0.7 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton::indicator:checked:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"RadioButton::indicator:disabled {\n"
"    border: 2px solid #bbbbbb;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"RadioButton::indicator:disabled:checked {\n"
"    border: none;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 rgba(0, 0, 0, 0.2169),\n"
"            stop:1 rgba(0, 0, 0, 0.2169));\n"
"}\n"
"\n"
"TransparentToolButton,\n"
"TransparentToggleToolButton,\n"
"TransparentDropDownToolButton,\n"
"TransparentPushButton,\n"
"TransparentDropDownPushButton,\n"
"TransparentTogglePushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"TransparentToolButton:hover,\n"
"TransparentToggleToolButton:hover,\n"
"TransparentDropDownToolButton:hover,\n"
"TransparentPushButton:hover,\n"
"TransparentDropDownPushButton:hover,\n"
"TransparentTogglePushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"TransparentToolButton:pressed,\n"
"TransparentToggleToolButton:pressed,\n"
"TransparentDropDownToolButton:pressed,\n"
"TransparentPushButton:pressed,\n"
"TransparentDropDownPushButton:pressed,\n"
"TransparentTogglePushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"TransparentToolButton:disabled,\n"
"TransparentToggleToolButton:disabled,\n"
"TransparentDropDownToolButton:disabled,\n"
"TransprentPushButton:disabled,\n"
"TransparentDropDownPushButton:disabled,\n"
"TransprentTogglePushButton:disabled {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"PillPushButton,\n"
"PillPushButton:hover,\n"
"PillPushButton:pressed,\n"
"PillPushButton:disabled,\n"
"PillPushButton:checked,\n"
"PillPushButton:checked:hover,\n"
"PillPushButton:checked:pressed,\n"
"PillPushButton:disabled:checked,\n"
"PillToolButton,\n"
"PillToolButton:hover,\n"
"PillToolButton:pressed,\n"
"PillToolButton:disabled,\n"
"PillToolButton:checked,\n"
"PillToolButton:checked:hover,\n"
"PillToolButton:checked:pressed,\n"
"PillToolButton:disabled:checked {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.DelManagedDirectory.setObjectName("DelManagedDirectory")
        self.poper.addWidget(self.page_4)
        self.Background = QtWidgets.QLabel(Form)
        self.Background.setGeometry(QtCore.QRect(0, 0, 811, 471))
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.Background.raise_()
        self.Navigation.raise_()
        self.poper.raise_()

        self.retranslateUi(Form)
        self.poper.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SubtitleLabel_3.setText(_translate("Form", "Line Minecraft 启动器"))
        self.SubtitleLabel_2.setText(_translate("Form", "启动"))
        self.CaptionLabel.setText(_translate("Form", "内存大小:"))
        self.CaptionLabel_2.setText(_translate("Form", "账户"))
        self.CaptionLabel_5.setText(_translate("Form", "Minecraft路径"))
        self.ManageMinecraft.setText(_translate("Form", "管理游戏"))
        self.AddMinecraftDirectory.setText(_translate("Form", "添加路径"))
        self.Launch.setProperty("text_", _translate("Form", "启动 {version}"))
        self.LoginTypeSwitcher.setText(_translate("Form", "离线登录"))
        self.SubtitleLabel.setText(_translate("Form", "账户管理"))
        self.Login.setText(_translate("Form", "登录"))
        self.Manage.setText(_translate("Form", "管理"))
        self.SubtitleLabel_4.setText(_translate("Form", "终端"))
        self.SubtitleLabel_5.setText(_translate("Form", "游戏下载与管理"))
        self.Download.setText(_translate("Form", "下载"))
        self.ManageDownloadedGame.setText(_translate("Form", "管理"))
        self.CurseForgeModDownload.setText(_translate("Form", "MOD"))
        self.BodyLabel_2.setText(_translate("Form", "CurseForge"))
        self.CurseForgePackagesDownload.setText(_translate("Form", "整合包"))
        self.SubtitleLabel_6.setText(_translate("Form", "设置"))
        self.BodyLabel_7.setText(_translate("Form", "下载源"))
        self.BodyLabel_12.setText(_translate("Form", "语言设定"))
        self.BodyLabel_8.setText(_translate("Form", "Java 选项"))
        self.BodyLabel_9.setText(_translate("Form", "游戏 Java 选择策略"))
        self.AddJavaManually.setText(_translate("Form", "手动添加"))
        self.BodyLabel_10.setText(_translate("Form", "强制使用的 Java (仅当策略为强制时可用)"))
        self.SearchJava.setText(_translate("Form", "搜索Java"))
        self.BodyLabel_11.setText(_translate("Form", "启动器可见性"))
        self.SubtitleLabel_7.setText(_translate("Form", "账户管理---登录"))
        self.MicrosoftLogin.setText(_translate("Form", "微软"))
        self.OfflinedLogin.setText(_translate("Form", "离线"))
        self.SubtitleLabel_8.setText(_translate("Form", "添加账户---微软"))
        self.AddAccount.setText(_translate("Form", "添加账户"))
        self.SubtitleLabel_9.setText(_translate("Form", "添加账户---离线"))
        self.CaptionLabel_4.setText(_translate("Form", "用户名"))
        self.ConfirmUsername.setText(_translate("Form", "确认"))
        self.ClearUsername.setText(_translate("Form", "清空"))
        self.ShowOldVersions.setText(_translate("Form", "显示远古"))
        self.ShowSnapshotVersions.setText(_translate("Form", "显示快照"))
        self.SubtitleLabel_10.setText(_translate("Form", "下载详情"))
        self.BodyLabel_3.setText(_translate("Form", "Forge"))
        self.BodyLabel_4.setText(_translate("Form", "Fabric"))
        self.BodyLabel_5.setText(_translate("Form", "Optifine"))
        self.BodyLabel_6.setText(_translate("Form", "OptiFabric Mod"))
        self.ConfirmDownload.setText(_translate("Form", "确认"))
        self.ClearOption.setText(_translate("Form", "清空"))
        self.ReturnPreviousStep.setText(_translate("Form", "返回"))
        self.SubtitleLabel_11.setText(_translate("Form", "Minecraft 路径管理"))
        self.SubtitleLabel_12.setText(_translate("Form", "版本详情"))
        self.MinecraftDirectoryManagement.setText(_translate("Form", "版本路径:"))
        self.OpenManagedMinecraftDircetory.setText(_translate("Form", "打开路径"))
        self.CurrentMinecrafts.setText(_translate("Form", "当前路径下的Minecraft:"))
        self.ManagementCustomName.setText(_translate("Form", "自定义名称:"))
        self.RenameMinecraftDirectory.setText(_translate("Form", "重命名"))
        self.DelManagedDirectory.setText(_translate("Form", "删除此路径"))
from qfluentwidgets import BodyLabel, CaptionLabel, CardWidget, CheckBox, ComboBox, EditableComboBox, LineEdit, ListWidget, NavigationInterface, PopUpAniStackedWidget, PrimarySplitPushButton, PushButton, Slider, SmoothScrollArea, SubtitleLabel, ToggleButton, TransparentPushButton
