# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'naming.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Naming(object):
    def setupUi(self, Naming):
        Naming.setObjectName("Naming")
        Naming.resize(400, 163)
        self.CaptionLabel = CaptionLabel(Naming)
        self.CaptionLabel.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.NameEdit = LineEdit(Naming)
        self.NameEdit.setGeometry(QtCore.QRect(10, 50, 371, 33))
        self.NameEdit.setObjectName("NameEdit")
        self.Confirm = PushButton(Naming)
        self.Confirm.setGeometry(QtCore.QRect(10, 110, 102, 32))
        self.Confirm.setObjectName("Confirm")
        self.Cancel = PushButton(Naming)
        self.Cancel.setGeometry(QtCore.QRect(280, 110, 102, 32))
        self.Cancel.setObjectName("Cancel")

        self.retranslateUi(Naming)
        QtCore.QMetaObject.connectSlotsByName(Naming)

    def retranslateUi(self, Naming):
        _translate = QtCore.QCoreApplication.translate
        Naming.setWindowTitle(_translate("Naming", "命名"))
        self.CaptionLabel.setText(_translate("Naming", "命名新目录"))
        self.Confirm.setText(_translate("Naming", "确认"))
        self.Cancel.setText(_translate("Naming", "取消"))
from qfluentwidgets import CaptionLabel, LineEdit, PushButton
