# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(802, 445)
        self.Navigation = NavigationInterface(Form)
        self.Navigation.setGeometry(QtCore.QRect(0, 10, 48, 461))
        self.Navigation.setObjectName("Navigation")
        self.poper = PopUpAniStackedWidget(Form)
        self.poper.setGeometry(QtCore.QRect(60, 10, 781, 421))
        self.poper.setObjectName("poper")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.SubtitleLabel_3 = SubtitleLabel(self.home)
        self.SubtitleLabel_3.setGeometry(QtCore.QRect(0, 10, 241, 28))
        self.SubtitleLabel_3.setObjectName("SubtitleLabel_3")
        self.BodyLabel = BodyLabel(self.home)
        self.BodyLabel.setGeometry(QtCore.QRect(0, 40, 711, 19))
        self.BodyLabel.setText("")
        self.BodyLabel.setObjectName("BodyLabel")
        self.poper.addWidget(self.home)
        self.launch = QtWidgets.QWidget()
        self.launch.setObjectName("launch")
        self.SubtitleLabel_2 = SubtitleLabel(self.launch)
        self.SubtitleLabel_2.setGeometry(QtCore.QRect(20, 10, 119, 28))
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.ConfirmLaunchingGame = PushButton(self.launch)
        self.ConfirmLaunchingGame.setGeometry(QtCore.QRect(511, 351, 191, 51))
        self.ConfirmLaunchingGame.setObjectName("ConfirmLaunchingGame")
        self.MemoryAdjuster = Slider(self.launch)
        self.MemoryAdjuster.setGeometry(QtCore.QRect(20, 360, 291, 31))
        self.MemoryAdjuster.setStyleSheet("QSlider:horizontal {\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 4px;\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #009faa;\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    border: 1px solid rgb(222, 222, 222);\n"
"    width: 20px;\n"
"    min-height: 24px;\n"
"    margin: -9px 0;\n"
"    border-radius: 11px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.48 #009faa,\n"
"        stop:0.55 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.55 #009faa,\n"
"        stop:0.65 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.4 #009faa,\n"
"        stop:0.5 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::groove:horizontal:disabled {\n"
"    background-color: rgba(0, 0, 0, 75);\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"    background-color: #808080;\n"
"    border: 5px solid #cccccc;\n"
"}\n"
"\n"
"\n"
"QSlider:vertical {\n"
"    min-width: 24px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    width: 4px;\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #009faa;\n"
"    width: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    border: 1px solid rgb(222, 222, 222);\n"
"    height: 20px;\n"
"    min-width: 24px;\n"
"    margin: 0 -9px;\n"
"    border-radius: 11px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.48 #009faa,\n"
"        stop:0.55 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.55 #009faa,\n"
"        stop:0.65 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.4 #009faa,\n"
"        stop:0.5 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::groove:vertical:disabled {\n"
"    background-color: rgba(0, 0, 0, 75);\n"
"}\n"
"\n"
"QSlider::handle:vertical:disabled {\n"
"    background-color: #808080;\n"
"    border: 5px solid #cccccc;\n"
"}\n"
"")
        self.MemoryAdjuster.setOrientation(QtCore.Qt.Horizontal)
        self.MemoryAdjuster.setObjectName("MemoryAdjuster")
        self.CaptionLabel = CaptionLabel(self.launch)
        self.CaptionLabel.setGeometry(QtCore.QRect(30, 340, 70, 15))
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.CaptionLabel_2 = CaptionLabel(self.launch)
        self.CaptionLabel_2.setGeometry(QtCore.QRect(30, 180, 91, 16))
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.CaptionLabel_5 = CaptionLabel(self.launch)
        self.CaptionLabel_5.setGeometry(QtCore.QRect(350, 180, 151, 16))
        self.CaptionLabel_5.setObjectName("CaptionLabel_5")
        self.ManageMinecraft = PushButton(self.launch)
        self.ManageMinecraft.setGeometry(QtCore.QRect(350, 240, 101, 32))
        self.ManageMinecraft.setObjectName("ManageMinecraft")
        self.AddMinecraftDirectory = PushButton(self.launch)
        self.AddMinecraftDirectory.setGeometry(QtCore.QRect(550, 240, 102, 32))
        self.AddMinecraftDirectory.setObjectName("AddMinecraftDirectory")
        self.CaptionLabel_6 = CaptionLabel(self.launch)
        self.CaptionLabel_6.setGeometry(QtCore.QRect(510, 280, 81, 16))
        self.CaptionLabel_6.setObjectName("CaptionLabel_6")
        self.groupBox = QtWidgets.QGroupBox(self.launch)
        self.groupBox.setGeometry(QtCore.QRect(20, 240, 261, 41))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.LaunchingMicrosoft = RadioButton(self.groupBox)
        self.LaunchingMicrosoft.setGeometry(QtCore.QRect(20, 0, 112, 24))
        self.LaunchingMicrosoft.setObjectName("LaunchingMicrosoft")
        self.LaunchingOfflined = RadioButton(self.groupBox)
        self.LaunchingOfflined.setGeometry(QtCore.QRect(150, 0, 112, 24))
        self.LaunchingOfflined.setObjectName("LaunchingOfflined")
        self.LaunchingAccountsSelector = EditableComboBox(self.launch)
        self.LaunchingAccountsSelector.setGeometry(QtCore.QRect(30, 200, 271, 33))
        self.LaunchingAccountsSelector.setObjectName("LaunchingAccountsSelector")
        self.LaunchingMinecraftDirectorySelector = EditableComboBox(self.launch)
        self.LaunchingMinecraftDirectorySelector.setGeometry(QtCore.QRect(350, 200, 321, 33))
        self.LaunchingMinecraftDirectorySelector.setObjectName("LaunchingMinecraftDirectorySelector")
        self.LaunchingVersion = EditableComboBox(self.launch)
        self.LaunchingVersion.setGeometry(QtCore.QRect(510, 320, 191, 33))
        self.LaunchingVersion.setObjectName("LaunchingVersion")
        self.memory_size_display = CaptionLabel(self.launch)
        self.memory_size_display.setGeometry(QtCore.QRect(90, 340, 70, 15))
        self.memory_size_display.setText("")
        self.memory_size_display.setObjectName("memory_size_display")
        self.poper.addWidget(self.launch)
        self.account = QtWidgets.QWidget()
        self.account.setObjectName("account")
        self.SubtitleLabel = SubtitleLabel(self.account)
        self.SubtitleLabel.setGeometry(QtCore.QRect(10, 10, 119, 28))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.Login = PushButton(self.account)
        self.Login.setGeometry(QtCore.QRect(10, 50, 102, 32))
        self.Login.setObjectName("Login")
        self.Manage = PushButton(self.account)
        self.Manage.setGeometry(QtCore.QRect(130, 50, 102, 32))
        self.Manage.setObjectName("Manage")
        self.poper.addWidget(self.account)
        self.terminal = QtWidgets.QWidget()
        self.terminal.setObjectName("terminal")
        self.SubtitleLabel_4 = SubtitleLabel(self.terminal)
        self.SubtitleLabel_4.setGeometry(QtCore.QRect(20, 10, 119, 28))
        self.SubtitleLabel_4.setObjectName("SubtitleLabel_4")
        self.poper.addWidget(self.terminal)
        self.download = QtWidgets.QWidget()
        self.download.setObjectName("download")
        self.SubtitleLabel_5 = SubtitleLabel(self.download)
        self.SubtitleLabel_5.setGeometry(QtCore.QRect(20, 10, 161, 28))
        self.SubtitleLabel_5.setObjectName("SubtitleLabel_5")
        self.Download = PushButton(self.download)
        self.Download.setGeometry(QtCore.QRect(20, 50, 102, 32))
        self.Download.setObjectName("Download")
        self.ManageDownloadedGame = PushButton(self.download)
        self.ManageDownloadedGame.setGeometry(QtCore.QRect(130, 50, 102, 32))
        self.ManageDownloadedGame.setObjectName("ManageDownloadedGame")
        self.CurseForgeModDownload = PushButton(self.download)
        self.CurseForgeModDownload.setGeometry(QtCore.QRect(30, 240, 102, 32))
        self.CurseForgeModDownload.setObjectName("CurseForgeModDownload")
        self.BodyLabel_2 = BodyLabel(self.download)
        self.BodyLabel_2.setGeometry(QtCore.QRect(40, 220, 111, 19))
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.CurseForgePackagesDownload = PushButton(self.download)
        self.CurseForgePackagesDownload.setGeometry(QtCore.QRect(150, 240, 102, 32))
        self.CurseForgePackagesDownload.setObjectName("CurseForgePackagesDownload")
        self.poper.addWidget(self.download)
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.SubtitleLabel_6 = SubtitleLabel(self.settings)
        self.SubtitleLabel_6.setGeometry(QtCore.QRect(10, 10, 119, 28))
        self.SubtitleLabel_6.setObjectName("SubtitleLabel_6")
        self.SmoothScrollArea = SmoothScrollArea(self.settings)
        self.SmoothScrollArea.setGeometry(QtCore.QRect(10, 50, 731, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SmoothScrollArea.sizePolicy().hasHeightForWidth())
        self.SmoothScrollArea.setSizePolicy(sizePolicy)
        self.SmoothScrollArea.setMinimumSize(QtCore.QSize(0, 200))
        self.SmoothScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SmoothScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SmoothScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SmoothScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -61, 718, 432))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DownloadSourceCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DownloadSourceCard.sizePolicy().hasHeightForWidth())
        self.DownloadSourceCard.setSizePolicy(sizePolicy)
        self.DownloadSourceCard.setMinimumSize(QtCore.QSize(700, 0))
        self.DownloadSourceCard.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DownloadSourceCard.setLineWidth(10)
        self.DownloadSourceCard.setObjectName("DownloadSourceCard")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.DownloadSourceCard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BodyLabel_7 = BodyLabel(self.DownloadSourceCard)
        self.BodyLabel_7.setObjectName("BodyLabel_7")
        self.verticalLayout.addWidget(self.BodyLabel_7)
        self.DownloadSourceSelector = ComboBox(self.DownloadSourceCard)
        self.DownloadSourceSelector.setObjectName("DownloadSourceSelector")
        self.verticalLayout.addWidget(self.DownloadSourceSelector)
        self.verticalLayout_2.addWidget(self.DownloadSourceCard)
        self.LanguageCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LanguageCard.sizePolicy().hasHeightForWidth())
        self.LanguageCard.setSizePolicy(sizePolicy)
        self.LanguageCard.setMinimumSize(QtCore.QSize(0, 100))
        self.LanguageCard.setObjectName("LanguageCard")
        self.BodyLabel_12 = BodyLabel(self.LanguageCard)
        self.BodyLabel_12.setGeometry(QtCore.QRect(10, 10, 63, 19))
        self.BodyLabel_12.setObjectName("BodyLabel_12")
        self.LanguageSelector = ComboBox(self.LanguageCard)
        self.LanguageSelector.setGeometry(QtCore.QRect(10, 50, 671, 32))
        self.LanguageSelector.setObjectName("LanguageSelector")
        self.verticalLayout_2.addWidget(self.LanguageCard)
        self.JavaCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JavaCard.sizePolicy().hasHeightForWidth())
        self.JavaCard.setSizePolicy(sizePolicy)
        self.JavaCard.setMinimumSize(QtCore.QSize(0, 150))
        self.JavaCard.setObjectName("JavaCard")
        self.BodyLabel_8 = BodyLabel(self.JavaCard)
        self.BodyLabel_8.setGeometry(QtCore.QRect(10, 10, 63, 19))
        self.BodyLabel_8.setObjectName("BodyLabel_8")
        self.BodyLabel_9 = BodyLabel(self.JavaCard)
        self.BodyLabel_9.setGeometry(QtCore.QRect(20, 80, 141, 19))
        self.BodyLabel_9.setObjectName("BodyLabel_9")
        self.JavaSelectionPlan = ComboBox(self.JavaCard)
        self.JavaSelectionPlan.setGeometry(QtCore.QRect(20, 110, 201, 32))
        self.JavaSelectionPlan.setObjectName("JavaSelectionPlan")
        self.AddJavaManually = PushButton(self.JavaCard)
        self.AddJavaManually.setGeometry(QtCore.QRect(230, 110, 102, 32))
        self.AddJavaManually.setObjectName("AddJavaManually")
        self.BodyLabel_10 = BodyLabel(self.JavaCard)
        self.BodyLabel_10.setGeometry(QtCore.QRect(360, 80, 301, 19))
        self.BodyLabel_10.setObjectName("BodyLabel_10")
        self.JavaForce = ComboBox(self.JavaCard)
        self.JavaForce.setGeometry(QtCore.QRect(360, 110, 301, 32))
        self.JavaForce.setObjectName("JavaForce")
        self.SearchJava = TransparentPushButton(self.JavaCard)
        self.SearchJava.setGeometry(QtCore.QRect(20, 50, 101, 30))
        self.SearchJava.setProperty("hasIcon", True)
        self.SearchJava.setObjectName("SearchJava")
        self.verticalLayout_2.addWidget(self.JavaCard)
        self.LauncherVisiableCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LauncherVisiableCard.sizePolicy().hasHeightForWidth())
        self.LauncherVisiableCard.setSizePolicy(sizePolicy)
        self.LauncherVisiableCard.setMinimumSize(QtCore.QSize(0, 70))
        self.LauncherVisiableCard.setObjectName("LauncherVisiableCard")
        self.BodyLabel_11 = BodyLabel(self.LauncherVisiableCard)
        self.BodyLabel_11.setGeometry(QtCore.QRect(10, 0, 131, 19))
        self.BodyLabel_11.setObjectName("BodyLabel_11")
        self.LauncherVisiableSelector = ComboBox(self.LauncherVisiableCard)
        self.LauncherVisiableSelector.setGeometry(QtCore.QRect(10, 30, 671, 32))
        self.LauncherVisiableSelector.setObjectName("LauncherVisiableSelector")
        self.verticalLayout_2.addWidget(self.LauncherVisiableCard)
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.poper.addWidget(self.settings)
        self.LoginSub = QtWidgets.QWidget()
        self.LoginSub.setObjectName("LoginSub")
        self.SubtitleLabel_7 = SubtitleLabel(self.LoginSub)
        self.SubtitleLabel_7.setGeometry(QtCore.QRect(10, 10, 171, 28))
        self.SubtitleLabel_7.setObjectName("SubtitleLabel_7")
        self.MicrosoftLogin = PushButton(self.LoginSub)
        self.MicrosoftLogin.setGeometry(QtCore.QRect(10, 70, 102, 32))
        self.MicrosoftLogin.setObjectName("MicrosoftLogin")
        self.OfflinedLogin = PushButton(self.LoginSub)
        self.OfflinedLogin.setGeometry(QtCore.QRect(140, 70, 102, 32))
        self.OfflinedLogin.setObjectName("OfflinedLogin")
        self.poper.addWidget(self.LoginSub)
        self.LoginSubPageMic = QtWidgets.QWidget()
        self.LoginSubPageMic.setObjectName("LoginSubPageMic")
        self.SubtitleLabel_8 = SubtitleLabel(self.LoginSubPageMic)
        self.SubtitleLabel_8.setGeometry(QtCore.QRect(10, 10, 201, 28))
        self.SubtitleLabel_8.setObjectName("SubtitleLabel_8")
        self.AddAccount = PushButton(self.LoginSubPageMic)
        self.AddAccount.setGeometry(QtCore.QRect(10, 100, 102, 32))
        self.AddAccount.setObjectName("AddAccount")
        self.RedirectedUrl = LineEdit(self.LoginSubPageMic)
        self.RedirectedUrl.setGeometry(QtCore.QRect(20, 220, 361, 33))
        self.RedirectedUrl.setObjectName("RedirectedUrl")
        self.CaptionLabel_3 = CaptionLabel(self.LoginSubPageMic)
        self.CaptionLabel_3.setGeometry(QtCore.QRect(20, 190, 70, 15))
        self.CaptionLabel_3.setObjectName("CaptionLabel_3")
        self.VerifyRedirectedUrl = PushButton(self.LoginSubPageMic)
        self.VerifyRedirectedUrl.setGeometry(QtCore.QRect(420, 220, 102, 32))
        self.VerifyRedirectedUrl.setObjectName("VerifyRedirectedUrl")
        self.poper.addWidget(self.LoginSubPageMic)
        self.LoginSubPageOffline = QtWidgets.QWidget()
        self.LoginSubPageOffline.setObjectName("LoginSubPageOffline")
        self.SubtitleLabel_9 = SubtitleLabel(self.LoginSubPageOffline)
        self.SubtitleLabel_9.setGeometry(QtCore.QRect(20, 10, 191, 28))
        self.SubtitleLabel_9.setObjectName("SubtitleLabel_9")
        self.CaptionLabel_4 = CaptionLabel(self.LoginSubPageOffline)
        self.CaptionLabel_4.setGeometry(QtCore.QRect(30, 70, 70, 15))
        self.CaptionLabel_4.setObjectName("CaptionLabel_4")
        self.Username = LineEdit(self.LoginSubPageOffline)
        self.Username.setGeometry(QtCore.QRect(30, 100, 391, 33))
        self.Username.setObjectName("Username")
        self.ConfirmUsername = PushButton(self.LoginSubPageOffline)
        self.ConfirmUsername.setGeometry(QtCore.QRect(30, 150, 102, 32))
        self.ConfirmUsername.setObjectName("ConfirmUsername")
        self.ClearUsername = PushButton(self.LoginSubPageOffline)
        self.ClearUsername.setGeometry(QtCore.QRect(320, 150, 102, 32))
        self.ClearUsername.setObjectName("ClearUsername")
        self.poper.addWidget(self.LoginSubPageOffline)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.VersionsView = ListWidget(self.page)
        self.VersionsView.setGeometry(QtCore.QRect(0, 0, 741, 361))
        self.VersionsView.setObjectName("VersionsView")
        self.ShowOldVersions = CheckBox(self.page)
        self.ShowOldVersions.setGeometry(QtCore.QRect(440, 380, 92, 22))
        self.ShowOldVersions.setObjectName("ShowOldVersions")
        self.ShowSnapshotVersions = CheckBox(self.page)
        self.ShowSnapshotVersions.setGeometry(QtCore.QRect(560, 380, 92, 22))
        self.ShowSnapshotVersions.setObjectName("ShowSnapshotVersions")
        self.poper.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.SubtitleLabel_10 = SubtitleLabel(self.page_2)
        self.SubtitleLabel_10.setGeometry(QtCore.QRect(10, 10, 119, 28))
        self.SubtitleLabel_10.setObjectName("SubtitleLabel_10")
        self.versionDisplay = BodyLabel(self.page_2)
        self.versionDisplay.setGeometry(QtCore.QRect(20, 60, 371, 19))
        self.versionDisplay.setText("")
        self.versionDisplay.setObjectName("versionDisplay")
        self.subProgramSelect = SmoothScrollArea(self.page_2)
        self.subProgramSelect.setGeometry(QtCore.QRect(10, 100, 691, 271))
        self.subProgramSelect.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.subProgramSelect.setLineWidth(1)
        self.subProgramSelect.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.subProgramSelect.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.subProgramSelect.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.subProgramSelect.setWidgetResizable(True)
        self.subProgramSelect.setObjectName("subProgramSelect")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 672, 269))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.ForgeSelector = ComboBox(self.scrollAreaWidgetContents_2)
        self.ForgeSelector.setGeometry(QtCore.QRect(0, 20, 671, 32))
        self.ForgeSelector.setObjectName("ForgeSelector")
        self.BodyLabel_3 = BodyLabel(self.scrollAreaWidgetContents_2)
        self.BodyLabel_3.setGeometry(QtCore.QRect(10, 0, 63, 19))
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.BodyLabel_4 = BodyLabel(self.scrollAreaWidgetContents_2)
        self.BodyLabel_4.setGeometry(QtCore.QRect(10, 60, 63, 19))
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.FabricSelector = ComboBox(self.scrollAreaWidgetContents_2)
        self.FabricSelector.setGeometry(QtCore.QRect(0, 90, 671, 32))
        self.FabricSelector.setObjectName("FabricSelector")
        self.BodyLabel_5 = BodyLabel(self.scrollAreaWidgetContents_2)
        self.BodyLabel_5.setGeometry(QtCore.QRect(10, 130, 63, 19))
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.OptifineSelector = ComboBox(self.scrollAreaWidgetContents_2)
        self.OptifineSelector.setGeometry(QtCore.QRect(10, 160, 661, 32))
        self.OptifineSelector.setObjectName("OptifineSelector")
        self.BodyLabel_6 = BodyLabel(self.scrollAreaWidgetContents_2)
        self.BodyLabel_6.setGeometry(QtCore.QRect(10, 200, 111, 19))
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.OptiFabricSelector = ComboBox(self.scrollAreaWidgetContents_2)
        self.OptiFabricSelector.setGeometry(QtCore.QRect(10, 230, 661, 32))
        self.OptiFabricSelector.setObjectName("OptiFabricSelector")
        self.subProgramSelect.setWidget(self.scrollAreaWidgetContents_2)
        self.ConfirmDownload = PushButton(self.page_2)
        self.ConfirmDownload.setGeometry(QtCore.QRect(600, 380, 102, 32))
        self.ConfirmDownload.setObjectName("ConfirmDownload")
        self.ClearOption = PushButton(self.page_2)
        self.ClearOption.setGeometry(QtCore.QRect(480, 380, 102, 32))
        self.ClearOption.setObjectName("ClearOption")
        self.ReturnPreviousStep = PushButton(self.page_2)
        self.ReturnPreviousStep.setGeometry(QtCore.QRect(360, 380, 102, 32))
        self.ReturnPreviousStep.setObjectName("ReturnPreviousStep")
        self.poper.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.poper.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SubtitleLabel_3.setText(_translate("Form", "Line Minecraft 启动器"))
        self.SubtitleLabel_2.setText(_translate("Form", "启动"))
        self.ConfirmLaunchingGame.setText(_translate("Form", "启动"))
        self.CaptionLabel.setText(_translate("Form", "内存大小:"))
        self.CaptionLabel_2.setText(_translate("Form", "选择一个用户"))
        self.CaptionLabel_5.setText(_translate("Form", "选择一个minecraft路径"))
        self.ManageMinecraft.setText(_translate("Form", "管理游戏..."))
        self.AddMinecraftDirectory.setText(_translate("Form", "添加目录"))
        self.CaptionLabel_6.setText(_translate("Form", "选择一个版本"))
        self.LaunchingMicrosoft.setText(_translate("Form", "微软登录"))
        self.LaunchingOfflined.setText(_translate("Form", "离线登录"))
        self.SubtitleLabel.setText(_translate("Form", "账户管理"))
        self.Login.setText(_translate("Form", "登录"))
        self.Manage.setText(_translate("Form", "管理"))
        self.SubtitleLabel_4.setText(_translate("Form", "终端"))
        self.SubtitleLabel_5.setText(_translate("Form", "游戏下载与管理"))
        self.Download.setText(_translate("Form", "下载"))
        self.ManageDownloadedGame.setText(_translate("Form", "管理"))
        self.CurseForgeModDownload.setText(_translate("Form", "MOD"))
        self.BodyLabel_2.setText(_translate("Form", "CurseForge"))
        self.CurseForgePackagesDownload.setText(_translate("Form", "整合包"))
        self.SubtitleLabel_6.setText(_translate("Form", "设置"))
        self.BodyLabel_7.setText(_translate("Form", "下载源"))
        self.BodyLabel_12.setText(_translate("Form", "语言设定"))
        self.BodyLabel_8.setText(_translate("Form", "Java 选项"))
        self.BodyLabel_9.setText(_translate("Form", "游戏 Java 选择策略"))
        self.AddJavaManually.setText(_translate("Form", "手动添加"))
        self.BodyLabel_10.setText(_translate("Form", "强制使用的 Java (仅当策略为强制时可用)"))
        self.SearchJava.setText(_translate("Form", "搜索Java"))
        self.BodyLabel_11.setText(_translate("Form", "启动器可见性"))
        self.SubtitleLabel_7.setText(_translate("Form", "账户管理---登录"))
        self.MicrosoftLogin.setText(_translate("Form", "微软"))
        self.OfflinedLogin.setText(_translate("Form", "离线"))
        self.SubtitleLabel_8.setText(_translate("Form", "添加账户---微软"))
        self.AddAccount.setText(_translate("Form", "添加账户"))
        self.CaptionLabel_3.setText(_translate("Form", "重定向的URL"))
        self.VerifyRedirectedUrl.setText(_translate("Form", "验证"))
        self.SubtitleLabel_9.setText(_translate("Form", "添加账户---离线"))
        self.CaptionLabel_4.setText(_translate("Form", "用户名"))
        self.ConfirmUsername.setText(_translate("Form", "确认"))
        self.ClearUsername.setText(_translate("Form", "清空"))
        self.ShowOldVersions.setText(_translate("Form", "显示远古"))
        self.ShowSnapshotVersions.setText(_translate("Form", "显示快照"))
        self.SubtitleLabel_10.setText(_translate("Form", "下载详情"))
        self.BodyLabel_3.setText(_translate("Form", "Forge"))
        self.BodyLabel_4.setText(_translate("Form", "Fabric"))
        self.BodyLabel_5.setText(_translate("Form", "Optifine"))
        self.BodyLabel_6.setText(_translate("Form", "OptiFabric Mod"))
        self.ConfirmDownload.setText(_translate("Form", "确认"))
        self.ClearOption.setText(_translate("Form", "清空"))
        self.ReturnPreviousStep.setText(_translate("Form", "返回"))
from qfluentwidgets import BodyLabel, CaptionLabel, CardWidget, CheckBox, ComboBox, EditableComboBox, LineEdit, ListWidget, NavigationInterface, PopUpAniStackedWidget, PushButton, RadioButton, Slider, SmoothScrollArea, SubtitleLabel, TransparentPushButton
