# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Coding\LineMinecraftLauncherProject\Refactor\Line\Interface\Interface\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LineMinecraftlauncher(object):
    def setupUi(self, LineMinecraftlauncher):
        LineMinecraftlauncher.setObjectName("LineMinecraftlauncher")
        LineMinecraftlauncher.resize(851, 475)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/LMC.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LineMinecraftlauncher.setWindowIcon(icon)
        self.poper = PopUpAniStackedWidget(LineMinecraftlauncher)
        self.poper.setGeometry(QtCore.QRect(70, 20, 741, 441))
        self.poper.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.poper.setObjectName("poper")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.SubtitleLabel_3 = SubtitleLabel(self.home)
        self.SubtitleLabel_3.setGeometry(QtCore.QRect(10, 10, 241, 28))
        self.SubtitleLabel_3.setObjectName("SubtitleLabel_3")
        self.BodyLabel = BodyLabel(self.home)
        self.BodyLabel.setGeometry(QtCore.QRect(0, 40, 711, 19))
        self.BodyLabel.setText("")
        self.BodyLabel.setObjectName("BodyLabel")
        self.poper.addWidget(self.home)
        self.launch = QtWidgets.QWidget()
        self.launch.setObjectName("launch")
        self.SubtitleLabel_2 = SubtitleLabel(self.launch)
        self.SubtitleLabel_2.setGeometry(QtCore.QRect(20, 10, 119, 28))
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.CaptionLabel_2 = CaptionLabel(self.launch)
        self.CaptionLabel_2.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.LaunchingAccountsSelector = EditableComboBox(self.launch)
        self.LaunchingAccountsSelector.setGeometry(QtCore.QRect(20, 80, 181, 33))
        self.LaunchingAccountsSelector.setObjectName("LaunchingAccountsSelector")
        self.Launch = PrimarySplitPushButton(self.launch)
        self.Launch.setGeometry(QtCore.QRect(20, 400, 141, 33))
        self.Launch.setObjectName("Launch")
        self.LoginTypeSwitcher = ToggleButton(self.launch)
        self.LoginTypeSwitcher.setGeometry(QtCore.QRect(210, 80, 113, 32))
        self.LoginTypeSwitcher.setObjectName("LoginTypeSwitcher")
        self.SimpleCardWidget = SimpleCardWidget(self.launch)
        self.SimpleCardWidget.setGeometry(QtCore.QRect(10, 50, 731, 81))
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.SimpleCardWidget_2 = SimpleCardWidget(self.launch)
        self.SimpleCardWidget_2.setGeometry(QtCore.QRect(10, 150, 731, 121))
        self.SimpleCardWidget_2.setObjectName("SimpleCardWidget_2")
        self.CaptionLabel_5 = CaptionLabel(self.SimpleCardWidget_2)
        self.CaptionLabel_5.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.CaptionLabel_5.setObjectName("CaptionLabel_5")
        self.MinecraftPathSelector = EditableComboBox(self.SimpleCardWidget_2)
        self.MinecraftPathSelector.setGeometry(QtCore.QRect(10, 30, 181, 33))
        self.MinecraftPathSelector.setObjectName("MinecraftPathSelector")
        self.ManageMinecraft = PushButton(self.SimpleCardWidget_2)
        self.ManageMinecraft.setGeometry(QtCore.QRect(10, 70, 101, 32))
        self.ManageMinecraft.setObjectName("ManageMinecraft")
        self.AddMinecraftDirectory = PushButton(self.SimpleCardWidget_2)
        self.AddMinecraftDirectory.setGeometry(QtCore.QRect(200, 30, 102, 32))
        self.AddMinecraftDirectory.setObjectName("AddMinecraftDirectory")
        self.SimpleCardWidget_3 = SimpleCardWidget(self.launch)
        self.SimpleCardWidget_3.setGeometry(QtCore.QRect(10, 290, 731, 91))
        self.SimpleCardWidget_3.setObjectName("SimpleCardWidget_3")
        self.MemorySizeDisplay = CaptionLabel(self.SimpleCardWidget_3)
        self.MemorySizeDisplay.setGeometry(QtCore.QRect(80, 10, 70, 15))
        self.MemorySizeDisplay.setObjectName("MemorySizeDisplay")
        self.CaptionLabel = CaptionLabel(self.SimpleCardWidget_3)
        self.CaptionLabel.setGeometry(QtCore.QRect(20, 10, 70, 15))
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.MemoryAdjuster = Slider(self.SimpleCardWidget_3)
        self.MemoryAdjuster.setGeometry(QtCore.QRect(10, 40, 291, 31))
        self.MemoryAdjuster.setStyleSheet("QSlider:horizontal {\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 4px;\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #009faa;\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    border: 1px solid rgb(222, 222, 222);\n"
"    width: 20px;\n"
"    min-height: 24px;\n"
"    margin: -9px 0;\n"
"    border-radius: 11px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.48 #009faa,\n"
"        stop:0.55 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.55 #009faa,\n"
"        stop:0.65 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.4 #009faa,\n"
"        stop:0.5 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::groove:horizontal:disabled {\n"
"    background-color: rgba(0, 0, 0, 75);\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"    background-color: #808080;\n"
"    border: 5px solid #cccccc;\n"
"}\n"
"\n"
"\n"
"QSlider:vertical {\n"
"    min-width: 24px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    width: 4px;\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #009faa;\n"
"    width: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    border: 1px solid rgb(222, 222, 222);\n"
"    height: 20px;\n"
"    min-width: 24px;\n"
"    margin: 0 -9px;\n"
"    border-radius: 11px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.48 #009faa,\n"
"        stop:0.55 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.55 #009faa,\n"
"        stop:0.65 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #009faa,\n"
"        stop:0.4 #009faa,\n"
"        stop:0.5 rgb(255, 255, 255),\n"
"        stop:1 rgb(255, 255, 255));\n"
"}\n"
"\n"
"QSlider::groove:vertical:disabled {\n"
"    background-color: rgba(0, 0, 0, 75);\n"
"}\n"
"\n"
"QSlider::handle:vertical:disabled {\n"
"    background-color: #808080;\n"
"    border: 5px solid #cccccc;\n"
"}\n"
"")
        self.MemoryAdjuster.setOrientation(QtCore.Qt.Horizontal)
        self.MemoryAdjuster.setObjectName("MemoryAdjuster")
        self.AutoMemoryManagement = CheckBox(self.SimpleCardWidget_3)
        self.AutoMemoryManagement.setGeometry(QtCore.QRect(320, 30, 271, 22))
        self.AutoMemoryManagement.setObjectName("AutoMemoryManagement")
        self.SimpleCardWidget_2.raise_()
        self.SimpleCardWidget.raise_()
        self.SubtitleLabel_2.raise_()
        self.CaptionLabel_2.raise_()
        self.LaunchingAccountsSelector.raise_()
        self.Launch.raise_()
        self.LoginTypeSwitcher.raise_()
        self.SimpleCardWidget_3.raise_()
        self.poper.addWidget(self.launch)
        self.account = QtWidgets.QWidget()
        self.account.setObjectName("account")
        self.SubtitleLabel = SubtitleLabel(self.account)
        self.SubtitleLabel.setGeometry(QtCore.QRect(10, 10, 119, 28))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.account)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 151, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.OfflinedLogin = PushButton(self.verticalLayoutWidget)
        self.OfflinedLogin.setToolTipDuration(0)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/IcBaselinePerson.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OfflinedLogin.setIcon(icon1)
        self.OfflinedLogin.setObjectName("OfflinedLogin")
        self.verticalLayout_5.addWidget(self.OfflinedLogin)
        self.MicrosoftLogin = PushButton(self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/MdiMicrosoft.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MicrosoftLogin.setIcon(icon2)
        self.MicrosoftLogin.setObjectName("MicrosoftLogin")
        self.verticalLayout_5.addWidget(self.MicrosoftLogin)
        self.LittleSkinLogin = PushButton(self.verticalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/MdiServer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LittleSkinLogin.setIcon(icon3)
        self.LittleSkinLogin.setObjectName("LittleSkinLogin")
        self.verticalLayout_5.addWidget(self.LittleSkinLogin)
        self.ExtraLogin = PushButton(self.verticalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/MaterialSymbolsLightDashboardCustomize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExtraLogin.setIcon(icon4)
        self.ExtraLogin.setObjectName("ExtraLogin")
        self.verticalLayout_5.addWidget(self.ExtraLogin)
        self.PopUpAniStackedWidget = PopUpAniStackedWidget(self.account)
        self.PopUpAniStackedWidget.setGeometry(QtCore.QRect(170, 40, 561, 391))
        self.PopUpAniStackedWidget.setObjectName("PopUpAniStackedWidget")
        self.OfflinedLogging = QtWidgets.QWidget()
        self.OfflinedLogging.setObjectName("OfflinedLogging")
        self.StrongBodyLabel_4 = StrongBodyLabel(self.OfflinedLogging)
        self.StrongBodyLabel_4.setGeometry(QtCore.QRect(20, 20, 111, 19))
        self.StrongBodyLabel_4.setObjectName("StrongBodyLabel_4")
        self.OfflinedUsernameEdit = LineEdit(self.OfflinedLogging)
        self.OfflinedUsernameEdit.setGeometry(QtCore.QRect(20, 50, 421, 33))
        self.OfflinedUsernameEdit.setText("")
        self.OfflinedUsernameEdit.setObjectName("OfflinedUsernameEdit")
        self.ConfirmOfflinedUsername = PushButton(self.OfflinedLogging)
        self.ConfirmOfflinedUsername.setGeometry(QtCore.QRect(20, 100, 102, 32))
        self.ConfirmOfflinedUsername.setObjectName("ConfirmOfflinedUsername")
        self.ClearOfflinedUsername = PushButton(self.OfflinedLogging)
        self.ClearOfflinedUsername.setGeometry(QtCore.QRect(340, 100, 102, 32))
        self.ClearOfflinedUsername.setObjectName("ClearOfflinedUsername")
        self.PopUpAniStackedWidget.addWidget(self.OfflinedLogging)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.TitleLabel = TitleLabel(self.page_5)
        self.TitleLabel.setGeometry(QtCore.QRect(10, 10, 411, 38))
        self.TitleLabel.setObjectName("TitleLabel")
        self.label = QtWidgets.QLabel(self.page_5)
        self.label.setGeometry(QtCore.QRect(10, 50, 541, 341))
        self.label.setStyleSheet("background: rgb(229, 222, 255);\n"
"border-radius: 10px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.IconWidget = IconWidget(self.page_5)
        self.IconWidget.setGeometry(QtCore.QRect(20, 60, 21, 21))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("f:\\Coding\\LineMinecraftLauncherProject\\Refactor\\Line\\Interface\\Interface\\../Icons/MaterialSymbolsLightNotificationImportant.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.IconWidget.setIcon(icon5)
        self.IconWidget.setObjectName("IconWidget")
        self.BodyLabel_15 = BodyLabel(self.page_5)
        self.BodyLabel_15.setGeometry(QtCore.QRect(50, 60, 63, 19))
        self.BodyLabel_15.setObjectName("BodyLabel_15")
        self.StrongBodyLabel_8 = StrongBodyLabel(self.page_5)
        self.StrongBodyLabel_8.setGeometry(QtCore.QRect(50, 90, 471, 41))
        self.StrongBodyLabel_8.setObjectName("StrongBodyLabel_8")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_5)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 140, 491, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CaptionLabel_3 = CaptionLabel(self.verticalLayoutWidget_2)
        self.CaptionLabel_3.setObjectName("CaptionLabel_3")
        self.verticalLayout_6.addWidget(self.CaptionLabel_3)
        self.CaptionLabel_4 = CaptionLabel(self.verticalLayoutWidget_2)
        self.CaptionLabel_4.setObjectName("CaptionLabel_4")
        self.verticalLayout_6.addWidget(self.CaptionLabel_4)
        self.CaptionLabel_6 = CaptionLabel(self.verticalLayoutWidget_2)
        self.CaptionLabel_6.setObjectName("CaptionLabel_6")
        self.verticalLayout_6.addWidget(self.CaptionLabel_6)
        self.CaptionLabel_7 = CaptionLabel(self.verticalLayoutWidget_2)
        self.CaptionLabel_7.setObjectName("CaptionLabel_7")
        self.verticalLayout_6.addWidget(self.CaptionLabel_7)
        self.CaptionLabel_8 = CaptionLabel(self.verticalLayoutWidget_2)
        self.CaptionLabel_8.setObjectName("CaptionLabel_8")
        self.verticalLayout_6.addWidget(self.CaptionLabel_8)
        self.CaptionLabel_9 = CaptionLabel(self.verticalLayoutWidget_2)
        self.CaptionLabel_9.setObjectName("CaptionLabel_9")
        self.verticalLayout_6.addWidget(self.CaptionLabel_9)
        self.ConfirmStartMicrosoftLogin = PushButton(self.page_5)
        self.ConfirmStartMicrosoftLogin.setGeometry(QtCore.QRect(221, 331, 311, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/MaterialSymbolsLightJumpToElement.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ConfirmStartMicrosoftLogin.setIcon(icon6)
        self.ConfirmStartMicrosoftLogin.setObjectName("ConfirmStartMicrosoftLogin")
        self.BuyMinecraft = PushButton(self.page_5)
        self.BuyMinecraft.setGeometry(QtCore.QRect(20, 330, 121, 41))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/MaterialSymbolsLightAddShoppingCart.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BuyMinecraft.setIcon(icon7)
        self.BuyMinecraft.setObjectName("BuyMinecraft")
        self.PopUpAniStackedWidget.addWidget(self.page_5)
        self.poper.addWidget(self.account)
        self.terminal = QtWidgets.QWidget()
        self.terminal.setObjectName("terminal")
        self.SubtitleLabel_4 = SubtitleLabel(self.terminal)
        self.SubtitleLabel_4.setGeometry(QtCore.QRect(20, 10, 119, 28))
        self.SubtitleLabel_4.setObjectName("SubtitleLabel_4")
        self.poper.addWidget(self.terminal)
        self.download = QtWidgets.QWidget()
        self.download.setObjectName("download")
        self.SubtitleLabel_5 = SubtitleLabel(self.download)
        self.SubtitleLabel_5.setGeometry(QtCore.QRect(20, 10, 161, 28))
        self.SubtitleLabel_5.setObjectName("SubtitleLabel_5")
        self.Download = PushButton(self.download)
        self.Download.setGeometry(QtCore.QRect(20, 50, 102, 32))
        self.Download.setObjectName("Download")
        self.CurseForgeModDownload = PushButton(self.download)
        self.CurseForgeModDownload.setGeometry(QtCore.QRect(30, 240, 102, 32))
        self.CurseForgeModDownload.setObjectName("CurseForgeModDownload")
        self.BodyLabel_2 = BodyLabel(self.download)
        self.BodyLabel_2.setGeometry(QtCore.QRect(40, 220, 111, 19))
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.CurseForgePackagesDownload = PushButton(self.download)
        self.CurseForgePackagesDownload.setGeometry(QtCore.QRect(150, 240, 102, 32))
        self.CurseForgePackagesDownload.setObjectName("CurseForgePackagesDownload")
        self.poper.addWidget(self.download)
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.SubtitleLabel_6 = SubtitleLabel(self.settings)
        self.SubtitleLabel_6.setGeometry(QtCore.QRect(10, 10, 119, 28))
        self.SubtitleLabel_6.setObjectName("SubtitleLabel_6")
        self.SmoothScrollArea = SmoothScrollArea(self.settings)
        self.SmoothScrollArea.setGeometry(QtCore.QRect(10, 40, 731, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SmoothScrollArea.sizePolicy().hasHeightForWidth())
        self.SmoothScrollArea.setSizePolicy(sizePolicy)
        self.SmoothScrollArea.setMinimumSize(QtCore.QSize(0, 200))
        self.SmoothScrollArea.setStyleSheet("background: transparent;\n"
"border-radius: 10px")
        self.SmoothScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SmoothScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SmoothScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SmoothScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 740, 916))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DownloadSourceCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DownloadSourceCard.sizePolicy().hasHeightForWidth())
        self.DownloadSourceCard.setSizePolicy(sizePolicy)
        self.DownloadSourceCard.setMinimumSize(QtCore.QSize(700, 0))
        self.DownloadSourceCard.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DownloadSourceCard.setLineWidth(10)
        self.DownloadSourceCard.setObjectName("DownloadSourceCard")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.DownloadSourceCard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BodyLabel_7 = BodyLabel(self.DownloadSourceCard)
        self.BodyLabel_7.setObjectName("BodyLabel_7")
        self.verticalLayout.addWidget(self.BodyLabel_7)
        self.DownloadSourceSelector = ComboBox(self.DownloadSourceCard)
        self.DownloadSourceSelector.setObjectName("DownloadSourceSelector")
        self.verticalLayout.addWidget(self.DownloadSourceSelector)
        self.verticalLayout_2.addWidget(self.DownloadSourceCard)
        self.LanguageCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LanguageCard.sizePolicy().hasHeightForWidth())
        self.LanguageCard.setSizePolicy(sizePolicy)
        self.LanguageCard.setMinimumSize(QtCore.QSize(0, 100))
        self.LanguageCard.setObjectName("LanguageCard")
        self.BodyLabel_12 = BodyLabel(self.LanguageCard)
        self.BodyLabel_12.setGeometry(QtCore.QRect(10, 10, 63, 19))
        self.BodyLabel_12.setObjectName("BodyLabel_12")
        self.LanguageSelector = ComboBox(self.LanguageCard)
        self.LanguageSelector.setGeometry(QtCore.QRect(10, 50, 671, 32))
        self.LanguageSelector.setObjectName("LanguageSelector")
        self.verticalLayout_2.addWidget(self.LanguageCard)
        self.JavaCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JavaCard.sizePolicy().hasHeightForWidth())
        self.JavaCard.setSizePolicy(sizePolicy)
        self.JavaCard.setMinimumSize(QtCore.QSize(0, 150))
        self.JavaCard.setObjectName("JavaCard")
        self.BodyLabel_8 = BodyLabel(self.JavaCard)
        self.BodyLabel_8.setGeometry(QtCore.QRect(10, 10, 63, 19))
        self.BodyLabel_8.setObjectName("BodyLabel_8")
        self.BodyLabel_9 = BodyLabel(self.JavaCard)
        self.BodyLabel_9.setGeometry(QtCore.QRect(20, 80, 141, 19))
        self.BodyLabel_9.setObjectName("BodyLabel_9")
        self.JavaSelectionPlan = ComboBox(self.JavaCard)
        self.JavaSelectionPlan.setGeometry(QtCore.QRect(20, 110, 201, 32))
        self.JavaSelectionPlan.setObjectName("JavaSelectionPlan")
        self.AddJavaManually = PushButton(self.JavaCard)
        self.AddJavaManually.setGeometry(QtCore.QRect(230, 110, 102, 32))
        self.AddJavaManually.setObjectName("AddJavaManually")
        self.BodyLabel_10 = BodyLabel(self.JavaCard)
        self.BodyLabel_10.setGeometry(QtCore.QRect(360, 80, 301, 19))
        self.BodyLabel_10.setObjectName("BodyLabel_10")
        self.JavaForce = ComboBox(self.JavaCard)
        self.JavaForce.setGeometry(QtCore.QRect(360, 110, 301, 32))
        self.JavaForce.setObjectName("JavaForce")
        self.SearchJava = PushButton(self.JavaCard)
        self.SearchJava.setGeometry(QtCore.QRect(20, 40, 161, 32))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/MaterialSymbolsLightSearch.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchJava.setIcon(icon8)
        self.SearchJava.setProperty("hasIcon", False)
        self.SearchJava.setObjectName("SearchJava")
        self.verticalLayout_2.addWidget(self.JavaCard)
        self.LauncherVisiableCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LauncherVisiableCard.sizePolicy().hasHeightForWidth())
        self.LauncherVisiableCard.setSizePolicy(sizePolicy)
        self.LauncherVisiableCard.setMinimumSize(QtCore.QSize(0, 100))
        self.LauncherVisiableCard.setObjectName("LauncherVisiableCard")
        self.BodyLabel_11 = BodyLabel(self.LauncherVisiableCard)
        self.BodyLabel_11.setGeometry(QtCore.QRect(10, 10, 131, 19))
        self.BodyLabel_11.setObjectName("BodyLabel_11")
        self.LauncherVisiableSelector = ComboBox(self.LauncherVisiableCard)
        self.LauncherVisiableSelector.setGeometry(QtCore.QRect(10, 40, 671, 32))
        self.LauncherVisiableSelector.setObjectName("LauncherVisiableSelector")
        self.verticalLayout_2.addWidget(self.LauncherVisiableCard)
        self.DownloaderSelectorCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DownloaderSelectorCard.sizePolicy().hasHeightForWidth())
        self.DownloaderSelectorCard.setSizePolicy(sizePolicy)
        self.DownloaderSelectorCard.setMinimumSize(QtCore.QSize(0, 250))
        self.DownloaderSelectorCard.setObjectName("DownloaderSelectorCard")
        self.BodyLabel_16 = BodyLabel(self.DownloaderSelectorCard)
        self.BodyLabel_16.setGeometry(QtCore.QRect(10, 10, 131, 19))
        self.BodyLabel_16.setObjectName("BodyLabel_16")
        self.DownloaderSelector = ComboBox(self.DownloaderSelectorCard)
        self.DownloaderSelector.setGeometry(QtCore.QRect(10, 40, 671, 32))
        self.DownloaderSelector.setObjectName("DownloaderSelector")
        self.BodyLabel_17 = BodyLabel(self.DownloaderSelectorCard)
        self.BodyLabel_17.setGeometry(QtCore.QRect(10, 90, 101, 19))
        self.BodyLabel_17.setObjectName("BodyLabel_17")
        self.Slider = Slider(self.DownloaderSelectorCard)
        self.Slider.setGeometry(QtCore.QRect(20, 130, 661, 21))
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName("Slider")
        self.StrongBodyLabel_10 = StrongBodyLabel(self.DownloaderSelectorCard)
        self.StrongBodyLabel_10.setGeometry(QtCore.QRect(40, 160, 111, 19))
        self.StrongBodyLabel_10.setObjectName("StrongBodyLabel_10")
        self.StrongBodyLabel_11 = StrongBodyLabel(self.DownloaderSelectorCard)
        self.StrongBodyLabel_11.setGeometry(QtCore.QRect(40, 190, 621, 19))
        self.StrongBodyLabel_11.setObjectName("StrongBodyLabel_11")
        self.verticalLayout_2.addWidget(self.DownloaderSelectorCard)
        self.LauncherBackgroundCard = CardWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LauncherBackgroundCard.sizePolicy().hasHeightForWidth())
        self.LauncherBackgroundCard.setSizePolicy(sizePolicy)
        self.LauncherBackgroundCard.setMinimumSize(QtCore.QSize(0, 100))
        self.LauncherBackgroundCard.setObjectName("LauncherBackgroundCard")
        self.BodyLabel_18 = BodyLabel(self.LauncherBackgroundCard)
        self.BodyLabel_18.setGeometry(QtCore.QRect(10, 10, 131, 19))
        self.BodyLabel_18.setObjectName("BodyLabel_18")
        self.LauncherBackgroundSelector = ComboBox(self.LauncherBackgroundCard)
        self.LauncherBackgroundSelector.setGeometry(QtCore.QRect(10, 40, 671, 32))
        self.LauncherBackgroundSelector.setObjectName("LauncherBackgroundSelector")
        self.verticalLayout_2.addWidget(self.LauncherBackgroundCard)
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.poper.addWidget(self.settings)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.VersionsView = ListWidget(self.page)
        self.VersionsView.setGeometry(QtCore.QRect(0, 100, 741, 281))
        self.VersionsView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    border-radius: 10px;\n"
"    background: rgb(255, 255, 255);\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.VersionsView.setObjectName("VersionsView")
        self.ShowOldVersions = CheckBox(self.page)
        self.ShowOldVersions.setGeometry(QtCore.QRect(490, 390, 92, 22))
        self.ShowOldVersions.setObjectName("ShowOldVersions")
        self.ShowSnapshotVersions = CheckBox(self.page)
        self.ShowSnapshotVersions.setGeometry(QtCore.QRect(610, 390, 92, 22))
        self.ShowSnapshotVersions.setObjectName("ShowSnapshotVersions")
        self.RefreshVersions = PushButton(self.page)
        self.RefreshVersions.setGeometry(QtCore.QRect(370, 390, 102, 32))
        self.RefreshVersions.setObjectName("RefreshVersions")
        self.SearchInVersionsView = LineEdit(self.page)
        self.SearchInVersionsView.setGeometry(QtCore.QRect(0, 50, 231, 33))
        self.SearchInVersionsView.setObjectName("SearchInVersionsView")
        self.poper.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.SubtitleLabel_10 = SubtitleLabel(self.page_2)
        self.SubtitleLabel_10.setGeometry(QtCore.QRect(10, 10, 119, 28))
        self.SubtitleLabel_10.setObjectName("SubtitleLabel_10")
        self.ConfirmDownload = PushButton(self.page_2)
        self.ConfirmDownload.setGeometry(QtCore.QRect(640, 380, 102, 32))
        self.ConfirmDownload.setObjectName("ConfirmDownload")
        self.ClearOption = PushButton(self.page_2)
        self.ClearOption.setGeometry(QtCore.QRect(530, 380, 102, 32))
        self.ClearOption.setObjectName("ClearOption")
        self.ReturnPreviousStep = PushButton(self.page_2)
        self.ReturnPreviousStep.setGeometry(QtCore.QRect(420, 380, 102, 32))
        self.ReturnPreviousStep.setObjectName("ReturnPreviousStep")
        self.CardWidget = CardWidget(self.page_2)
        self.CardWidget.setGeometry(QtCore.QRect(20, 40, 711, 81))
        self.CardWidget.setObjectName("CardWidget")
        self.BodyLabel_4 = BodyLabel(self.CardWidget)
        self.BodyLabel_4.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.InstallationName = LineEdit(self.CardWidget)
        self.InstallationName.setGeometry(QtCore.QRect(50, 10, 161, 33))
        self.InstallationName.setObjectName("InstallationName")
        self.IsNameAvailable = BodyLabel(self.CardWidget)
        self.IsNameAvailable.setGeometry(QtCore.QRect(50, 50, 121, 19))
        self.IsNameAvailable.setObjectName("IsNameAvailable")
        self.SmoothScrollArea_2 = SmoothScrollArea(self.page_2)
        self.SmoothScrollArea_2.setGeometry(QtCore.QRect(0, 130, 731, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SmoothScrollArea_2.sizePolicy().hasHeightForWidth())
        self.SmoothScrollArea_2.setSizePolicy(sizePolicy)
        self.SmoothScrollArea_2.setMinimumSize(QtCore.QSize(600, 200))
        self.SmoothScrollArea_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.SmoothScrollArea_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SmoothScrollArea_2.setAutoFillBackground(False)
        self.SmoothScrollArea_2.setStyleSheet("background: transparent;\n"
"border-radius: 5px")
        self.SmoothScrollArea_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SmoothScrollArea_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SmoothScrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SmoothScrollArea_2.setWidgetResizable(True)
        self.SmoothScrollArea_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.SmoothScrollArea_2.setObjectName("SmoothScrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 729, 1143))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.CardWidget_3 = CardWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_3.sizePolicy().hasHeightForWidth())
        self.CardWidget_3.setSizePolicy(sizePolicy)
        self.CardWidget_3.setMinimumSize(QtCore.QSize(650, 200))
        self.CardWidget_3.setMaximumSize(QtCore.QSize(650, 16777215))
        self.CardWidget_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.CardWidget_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_3.setStyleSheet("")
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.BodyLabel_3 = BodyLabel(self.CardWidget_3)
        self.BodyLabel_3.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.Forge = LineEdit(self.CardWidget_3)
        self.Forge.setGeometry(QtCore.QRect(60, 10, 291, 33))
        self.Forge.setObjectName("Forge")
        self.ForgeView = ListWidget(self.CardWidget_3)
        self.ForgeView.setGeometry(QtCore.QRect(60, 60, 561, 121))
        self.ForgeView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    outline: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 5px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.ForgeView.setObjectName("ForgeView")
        self.verticalLayout_3.addWidget(self.CardWidget_3)
        self.CardWidget_4 = CardWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_4.sizePolicy().hasHeightForWidth())
        self.CardWidget_4.setSizePolicy(sizePolicy)
        self.CardWidget_4.setMinimumSize(QtCore.QSize(650, 200))
        self.CardWidget_4.setMaximumSize(QtCore.QSize(650, 16777215))
        self.CardWidget_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.CardWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_4.setStyleSheet("")
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.BodyLabel_5 = BodyLabel(self.CardWidget_4)
        self.BodyLabel_5.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.Optifine = LineEdit(self.CardWidget_4)
        self.Optifine.setGeometry(QtCore.QRect(70, 10, 291, 33))
        self.Optifine.setObjectName("Optifine")
        self.OptifineView = ListWidget(self.CardWidget_4)
        self.OptifineView.setGeometry(QtCore.QRect(60, 60, 561, 121))
        self.OptifineView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.OptifineView.setObjectName("OptifineView")
        self.verticalLayout_3.addWidget(self.CardWidget_4)
        self.CardWidget_5 = CardWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_5.sizePolicy().hasHeightForWidth())
        self.CardWidget_5.setSizePolicy(sizePolicy)
        self.CardWidget_5.setMinimumSize(QtCore.QSize(650, 200))
        self.CardWidget_5.setMaximumSize(QtCore.QSize(650, 16777215))
        self.CardWidget_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.CardWidget_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_5.setStyleSheet("")
        self.CardWidget_5.setObjectName("CardWidget_5")
        self.BodyLabel_6 = BodyLabel(self.CardWidget_5)
        self.BodyLabel_6.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.Fabric = LineEdit(self.CardWidget_5)
        self.Fabric.setGeometry(QtCore.QRect(60, 10, 291, 33))
        self.Fabric.setObjectName("Fabric")
        self.FabricView = ListWidget(self.CardWidget_5)
        self.FabricView.setGeometry(QtCore.QRect(60, 60, 561, 121))
        self.FabricView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.FabricView.setObjectName("FabricView")
        self.verticalLayout_3.addWidget(self.CardWidget_5)
        self.CardWidget_6 = CardWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_6.sizePolicy().hasHeightForWidth())
        self.CardWidget_6.setSizePolicy(sizePolicy)
        self.CardWidget_6.setMinimumSize(QtCore.QSize(650, 200))
        self.CardWidget_6.setMaximumSize(QtCore.QSize(650, 16777215))
        self.CardWidget_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.CardWidget_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_6.setStyleSheet("")
        self.CardWidget_6.setObjectName("CardWidget_6")
        self.BodyLabel_13 = BodyLabel(self.CardWidget_6)
        self.BodyLabel_13.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.BodyLabel_13.setObjectName("BodyLabel_13")
        self.Optifabric = LineEdit(self.CardWidget_6)
        self.Optifabric.setGeometry(QtCore.QRect(80, 10, 291, 33))
        self.Optifabric.setObjectName("Optifabric")
        self.OptifabricView = ListWidget(self.CardWidget_6)
        self.OptifabricView.setGeometry(QtCore.QRect(60, 60, 561, 121))
        self.OptifabricView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.OptifabricView.setObjectName("OptifabricView")
        self.verticalLayout_3.addWidget(self.CardWidget_6)
        self.CardWidget_7 = CardWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_7.sizePolicy().hasHeightForWidth())
        self.CardWidget_7.setSizePolicy(sizePolicy)
        self.CardWidget_7.setMinimumSize(QtCore.QSize(650, 200))
        self.CardWidget_7.setMaximumSize(QtCore.QSize(650, 16777215))
        self.CardWidget_7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.CardWidget_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_7.setStyleSheet("")
        self.CardWidget_7.setObjectName("CardWidget_7")
        self.BodyLabel_14 = BodyLabel(self.CardWidget_7)
        self.BodyLabel_14.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.BodyLabel_14.setObjectName("BodyLabel_14")
        self.FabricAPI = LineEdit(self.CardWidget_7)
        self.FabricAPI.setGeometry(QtCore.QRect(80, 10, 291, 33))
        self.FabricAPI.setObjectName("FabricAPI")
        self.FabricAPIView = ListWidget(self.CardWidget_7)
        self.FabricAPIView.setGeometry(QtCore.QRect(60, 60, 561, 121))
        self.FabricAPIView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.FabricAPIView.setObjectName("FabricAPIView")
        self.verticalLayout_3.addWidget(self.CardWidget_7)
        self.HorizontalSeparator = HorizontalSeparator(self.scrollAreaWidgetContents_2)
        self.HorizontalSeparator.setObjectName("HorizontalSeparator")
        self.verticalLayout_3.addWidget(self.HorizontalSeparator)
        self.SmoothScrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.poper.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.SubtitleLabel_11 = SubtitleLabel(self.page_3)
        self.SubtitleLabel_11.setGeometry(QtCore.QRect(10, 10, 211, 28))
        self.SubtitleLabel_11.setObjectName("SubtitleLabel_11")
        self.MinecraftDirectoriesManagementView = ListWidget(self.page_3)
        self.MinecraftDirectoriesManagementView.setGeometry(QtCore.QRect(10, 90, 731, 331))
        self.MinecraftDirectoriesManagementView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: white;\n"
"    border-radius: 10px;\n"
"    outline: none;\n"
"    border: none;\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    font: 75 italic 12pt \"MS Sans Serif\";\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(108, 95, 154);\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"ListView::indicator:hover,\n"
"ListWidget::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"ListView::indicator:pressed,\n"
"ListWidget::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"ListView::indicator:checke,\n"
"ListWidget::indicator:checked,\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"ListView::indicator:checked,\n"
"ListWidget::indicator:checked {\n"
"    image: url(:/qfluentwidgets/images/check_box/Accept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    image: url(:/qfluentwidgets/images/check_box/PartialAccept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:checked:hove,\n"
"ListWidget::indicator:checked:hover,\n"
"ListView::indicator:indeterminate:hover,\n"
"ListWidget::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"ListView::indicator:checked:presse,\n"
"ListWidget::indicator:checked:pressed,\n"
"ListView::indicator:indeterminate:pressed,\n"
"ListWidget::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"ListView::indicator:disabled,\n"
"ListWidget::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"ListView::indicator:checked:disable,\n"
"ListWidget::indicator:checked:disabled,\n"
"ListView::indicator:indeterminate:disabled,\n"
"ListWidget::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.MinecraftDirectoriesManagementView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MinecraftDirectoriesManagementView.setObjectName("MinecraftDirectoriesManagementView")
        self.StrongBodyLabel_9 = StrongBodyLabel(self.page_3)
        self.StrongBodyLabel_9.setGeometry(QtCore.QRect(20, 60, 201, 19))
        self.StrongBodyLabel_9.setObjectName("StrongBodyLabel_9")
        self.poper.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.SubtitleLabel_12 = SubtitleLabel(self.page_4)
        self.SubtitleLabel_12.setGeometry(QtCore.QRect(20, 10, 119, 28))
        self.SubtitleLabel_12.setObjectName("SubtitleLabel_12")
        self.CurrentMinecraftsView = ListWidget(self.page_4)
        self.CurrentMinecraftsView.setGeometry(QtCore.QRect(30, 290, 731, 111))
        self.CurrentMinecraftsView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: transparent;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    font: 75 italic 12pt \"MS Sans Serif\";\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(108, 95, 154);\n"
"    background: transparent;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"ListView::indicator:hover,\n"
"ListWidget::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"ListView::indicator:pressed,\n"
"ListWidget::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"ListView::indicator:checke,\n"
"ListWidget::indicator:checked,\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"ListView::indicator:checked,\n"
"ListWidget::indicator:checked {\n"
"    image: url(:/qfluentwidgets/images/check_box/Accept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    image: url(:/qfluentwidgets/images/check_box/PartialAccept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:checked:hove,\n"
"ListWidget::indicator:checked:hover,\n"
"ListView::indicator:indeterminate:hover,\n"
"ListWidget::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"ListView::indicator:checked:presse,\n"
"ListWidget::indicator:checked:pressed,\n"
"ListView::indicator:indeterminate:pressed,\n"
"ListWidget::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"ListView::indicator:disabled,\n"
"ListWidget::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"ListView::indicator:checked:disable,\n"
"ListWidget::indicator:checked:disabled,\n"
"ListView::indicator:indeterminate:disabled,\n"
"ListWidget::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CurrentMinecraftsView.setObjectName("CurrentMinecraftsView")
        self.SmoothScrollArea_3 = SmoothScrollArea(self.page_4)
        self.SmoothScrollArea_3.setGeometry(QtCore.QRect(20, 50, 721, 381))
        self.SmoothScrollArea_3.setMaximumSize(QtCore.QSize(721, 381))
        self.SmoothScrollArea_3.setStyleSheet("background: transparent;\n"
"border-radius: 5px")
        self.SmoothScrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SmoothScrollArea_3.setWidgetResizable(True)
        self.SmoothScrollArea_3.setObjectName("SmoothScrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 719, 1420))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.CardWidget_2 = CardWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_2.sizePolicy().hasHeightForWidth())
        self.CardWidget_2.setSizePolicy(sizePolicy)
        self.CardWidget_2.setMinimumSize(QtCore.QSize(0, 100))
        self.CardWidget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.StrongBodyLabel = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(10, 10, 111, 19))
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.ManagedVersion = LineEdit(self.CardWidget_2)
        self.ManagedVersion.setGeometry(QtCore.QRect(80, 10, 291, 33))
        self.ManagedVersion.setObjectName("ManagedVersion")
        self.ConfirmNewManagedVersionID = PushButton(self.CardWidget_2)
        self.ConfirmNewManagedVersionID.setGeometry(QtCore.QRect(80, 60, 102, 32))
        self.ConfirmNewManagedVersionID.setObjectName("ConfirmNewManagedVersionID")
        self.CancelNewManagedVersionID = PushButton(self.CardWidget_2)
        self.CancelNewManagedVersionID.setGeometry(QtCore.QRect(260, 60, 102, 32))
        self.CancelNewManagedVersionID.setObjectName("CancelNewManagedVersionID")
        self.IsNewManagedVersionIDAvail = StrongBodyLabel(self.CardWidget_2)
        self.IsNewManagedVersionIDAvail.setGeometry(QtCore.QRect(380, 20, 111, 19))
        self.IsNewManagedVersionIDAvail.setObjectName("IsNewManagedVersionIDAvail")
        self.verticalLayout_4.addWidget(self.CardWidget_2)
        self.CardWidget_8 = CardWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_8.sizePolicy().hasHeightForWidth())
        self.CardWidget_8.setSizePolicy(sizePolicy)
        self.CardWidget_8.setMinimumSize(QtCore.QSize(0, 200))
        self.CardWidget_8.setMaximumSize(QtCore.QSize(16777215, 200))
        self.CardWidget_8.setObjectName("CardWidget_8")
        self.StrongBodyLabel_2 = StrongBodyLabel(self.CardWidget_8)
        self.StrongBodyLabel_2.setGeometry(QtCore.QRect(10, 10, 111, 19))
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.StrongBodyLabel_7 = StrongBodyLabel(self.CardWidget_8)
        self.StrongBodyLabel_7.setGeometry(QtCore.QRect(40, 30, 271, 19))
        self.StrongBodyLabel_7.setObjectName("StrongBodyLabel_7")
        self.ManagedVersionCheckList = ListWidget(self.CardWidget_8)
        self.ManagedVersionCheckList.setGeometry(QtCore.QRect(40, 60, 591, 121))
        self.ManagedVersionCheckList.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: white;\n"
"    border-radius: 10px;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.ManagedVersionCheckList.setObjectName("ManagedVersionCheckList")
        self.verticalLayout_4.addWidget(self.CardWidget_8)
        self.CardWidget_9 = CardWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_9.sizePolicy().hasHeightForWidth())
        self.CardWidget_9.setSizePolicy(sizePolicy)
        self.CardWidget_9.setMinimumSize(QtCore.QSize(0, 200))
        self.CardWidget_9.setMaximumSize(QtCore.QSize(16777215, 200))
        self.CardWidget_9.setObjectName("CardWidget_9")
        self.StrongBodyLabel_3 = StrongBodyLabel(self.CardWidget_9)
        self.StrongBodyLabel_3.setGeometry(QtCore.QRect(10, 10, 111, 19))
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.OpenManagedVersionDir = PushButton(self.CardWidget_9)
        self.OpenManagedVersionDir.setGeometry(QtCore.QRect(40, 40, 141, 32))
        self.OpenManagedVersionDir.setObjectName("OpenManagedVersionDir")
        self.OpenManagedVersionSavesDir = PushButton(self.CardWidget_9)
        self.OpenManagedVersionSavesDir.setGeometry(QtCore.QRect(200, 40, 141, 32))
        self.OpenManagedVersionSavesDir.setObjectName("OpenManagedVersionSavesDir")
        self.GenerateManagedVersionLaunchingScript = PushButton(self.CardWidget_9)
        self.GenerateManagedVersionLaunchingScript.setGeometry(QtCore.QRect(40, 90, 141, 32))
        self.GenerateManagedVersionLaunchingScript.setObjectName("GenerateManagedVersionLaunchingScript")
        self.CleanManagedVersionDir = PushButton(self.CardWidget_9)
        self.CleanManagedVersionDir.setGeometry(QtCore.QRect(40, 140, 141, 32))
        self.CleanManagedVersionDir.setObjectName("CleanManagedVersionDir")
        self.DelManagedVersion = PushButton(self.CardWidget_9)
        self.DelManagedVersion.setGeometry(QtCore.QRect(510, 150, 141, 32))
        self.DelManagedVersion.setStyleSheet("PushButton, ToolButton, ToggleButton, ToggleToolButton {\n"
"    color: rgb(255, 0, 0);\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"ToolButton {\n"
"    padding: 5px 9px 6px 8px;\n"
"}\n"
"\n"
"PushButton[isPlaceholderText=true] {\n"
"    color: rgba(0, 0, 0, 0.6063);\n"
"}\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"DropDownToolButton, PrimaryDropDownToolButton {\n"
"    padding: 5px 31px 6px 8px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"PushButton:pressed, ToolButton:pressed, ToggleButton:pressed, ToggleToolButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"PushButton:disabled, ToolButton:disabled, ToggleButton:disabled, ToggleToolButton:disabled {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"\n"
"\n"
"PrimaryPushButton,\n"
"PrimaryToolButton,\n"
"ToggleButton:checked,\n"
"ToggleToolButton:checked {\n"
"    color: white;\n"
"    background-color: #009faa;\n"
"    border: 1px solid #00a7b3;\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"PrimaryPushButton:hover,\n"
"PrimaryToolButton:hover,\n"
"ToggleButton:checked:hover,\n"
"ToggleToolButton:checked:hover {\n"
"    background-color: #00a7b3;\n"
"    border: 1px solid #2daab3;\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"PrimaryPushButton:pressed,\n"
"PrimaryToolButton:pressed,\n"
"ToggleButton:checked:pressed,\n"
"ToggleToolButton:checked:pressed {\n"
"    color: rgba(255, 255, 255, 0.63);\n"
"    background-color: #3eabb3;\n"
"    border: 1px solid #3eabb3;\n"
"}\n"
"\n"
"PrimaryPushButton:disabled,\n"
"PrimaryToolButton:disabled,\n"
"ToggleButton:checked:disabled,\n"
"ToggleToolButton:checked:disabled {\n"
"    color: rgba(255, 255, 255, 0.9);\n"
"    background-color: rgb(205, 205, 205);\n"
"    border: 1px solid rgb(205, 205, 205);\n"
"}\n"
"\n"
"SplitDropButton,\n"
"PrimarySplitDropButton {\n"
"    border-left: none;\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"}\n"
"\n"
"#splitPushButton,\n"
"#splitToolButton,\n"
"#primarySplitPushButton,\n"
"#primarySplitToolButton {\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"}\n"
"\n"
"#splitPushButton:pressed,\n"
"#splitToolButton:pressed,\n"
"SplitDropButton:pressed {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"}\n"
"\n"
"PrimarySplitDropButton:pressed {\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"#primarySplitPushButton, #primarySplitToolButton {\n"
"    border-right: 1px solid #3eabb3;\n"
"}\n"
"\n"
"#primarySplitPushButton:pressed, #primarySplitToolButton:pressed {\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"HyperlinkButton {\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 6px 12px 6px 12px;\n"
"    color: #009faa;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"HyperlinkButton[hasIcon=false] {\n"
"    padding: 6px 12px 6px 12px;\n"
"}\n"
"\n"
"HyperlinkButton[hasIcon=true] {\n"
"    padding: 6px 12px 6px 36px;\n"
"}\n"
"\n"
"HyperlinkButton:hover {\n"
"    color: #009faa;\n"
"    background-color: rgba(0, 0, 0, 10);\n"
"    border: none;\n"
"}\n"
"\n"
"HyperlinkButton:pressed {\n"
"    color: #009faa;\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"HyperlinkButton:disabled {\n"
"    color: rgba(0, 0, 0, 0.43);\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"RadioButton {\n"
"    min-height: 24px;\n"
"    max-height: 24px;\n"
"    background-color: transparent;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    color: black;\n"
"}\n"
"\n"
"RadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 11px;\n"
"    border: 2px solid #999999;\n"
"    background-color: rgba(0, 0, 0, 5);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"RadioButton::indicator:hover {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"RadioButton::indicator:pressed {\n"
"    border: 2px solid #bbbbbb;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 rgb(225, 224, 223),\n"
"            stop:1 rgb(225, 224, 223));\n"
"}\n"
"\n"
"RadioButton::indicator:checked {\n"
"    height: 22px;\n"
"    width: 22px;\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton::indicator:checked:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.6 rgb(255, 255, 255),\n"
"            stop:0.7 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton::indicator:checked:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"RadioButton::indicator:disabled {\n"
"    border: 2px solid #bbbbbb;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"RadioButton::indicator:disabled:checked {\n"
"    border: none;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 rgba(0, 0, 0, 0.2169),\n"
"            stop:1 rgba(0, 0, 0, 0.2169));\n"
"}\n"
"\n"
"TransparentToolButton,\n"
"TransparentToggleToolButton,\n"
"TransparentDropDownToolButton,\n"
"TransparentPushButton,\n"
"TransparentDropDownPushButton,\n"
"TransparentTogglePushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"TransparentToolButton:hover,\n"
"TransparentToggleToolButton:hover,\n"
"TransparentDropDownToolButton:hover,\n"
"TransparentPushButton:hover,\n"
"TransparentDropDownPushButton:hover,\n"
"TransparentTogglePushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"TransparentToolButton:pressed,\n"
"TransparentToggleToolButton:pressed,\n"
"TransparentDropDownToolButton:pressed,\n"
"TransparentPushButton:pressed,\n"
"TransparentDropDownPushButton:pressed,\n"
"TransparentTogglePushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"TransparentToolButton:disabled,\n"
"TransparentToggleToolButton:disabled,\n"
"TransparentDropDownToolButton:disabled,\n"
"TransparentPushButton:disabled,\n"
"TransparentDropDownPushButton:disabled,\n"
"TransparentTogglePushButton:disabled {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"PillPushButton,\n"
"PillPushButton:hover,\n"
"PillPushButton:pressed,\n"
"PillPushButton:disabled,\n"
"PillPushButton:checked,\n"
"PillPushButton:checked:hover,\n"
"PillPushButton:checked:pressed,\n"
"PillPushButton:disabled:checked,\n"
"PillToolButton,\n"
"PillToolButton:hover,\n"
"PillToolButton:pressed,\n"
"PillToolButton:disabled,\n"
"PillToolButton:checked,\n"
"PillToolButton:checked:hover,\n"
"PillToolButton:checked:pressed,\n"
"PillToolButton:disabled:checked {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.DelManagedVersion.setObjectName("DelManagedVersion")
        self.verticalLayout_4.addWidget(self.CardWidget_9)
        self.CardWidget_11 = CardWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_11.sizePolicy().hasHeightForWidth())
        self.CardWidget_11.setSizePolicy(sizePolicy)
        self.CardWidget_11.setMinimumSize(QtCore.QSize(0, 400))
        self.CardWidget_11.setMaximumSize(QtCore.QSize(16777215, 400))
        self.CardWidget_11.setObjectName("CardWidget_11")
        self.StrongBodyLabel_5 = StrongBodyLabel(self.CardWidget_11)
        self.StrongBodyLabel_5.setGeometry(QtCore.QRect(10, 10, 111, 19))
        self.StrongBodyLabel_5.setObjectName("StrongBodyLabel_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.CardWidget_11)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 641, 73))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ImportManagedVersionMod = PushButton(self.horizontalLayoutWidget)
        self.ImportManagedVersionMod.setObjectName("ImportManagedVersionMod")
        self.horizontalLayout.addWidget(self.ImportManagedVersionMod)
        self.RefreshManagedVersionMod = PushButton(self.horizontalLayoutWidget)
        self.RefreshManagedVersionMod.setObjectName("RefreshManagedVersionMod")
        self.horizontalLayout.addWidget(self.RefreshManagedVersionMod)
        self.OpenManagedVersionModDir = PushButton(self.horizontalLayoutWidget)
        self.OpenManagedVersionModDir.setObjectName("OpenManagedVersionModDir")
        self.horizontalLayout.addWidget(self.OpenManagedVersionModDir)
        self.JumpDownloadingModForManagedVersion = PushButton(self.horizontalLayoutWidget)
        self.JumpDownloadingModForManagedVersion.setObjectName("JumpDownloadingModForManagedVersion")
        self.horizontalLayout.addWidget(self.JumpDownloadingModForManagedVersion)
        self.SearchManagedVersionMod = SearchLineEdit(self.horizontalLayoutWidget)
        self.SearchManagedVersionMod.setObjectName("SearchManagedVersionMod")
        self.horizontalLayout.addWidget(self.SearchManagedVersionMod)
        self.ManagedVersionModView = ListWidget(self.CardWidget_11)
        self.ManagedVersionModView.setGeometry(QtCore.QRect(30, 120, 611, 261))
        self.ManagedVersionModView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: white;\n"
"    border-radius: 10px;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.ManagedVersionModView.setObjectName("ManagedVersionModView")
        self.verticalLayout_4.addWidget(self.CardWidget_11)
        self.CardWidget_12 = CardWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_12.sizePolicy().hasHeightForWidth())
        self.CardWidget_12.setSizePolicy(sizePolicy)
        self.CardWidget_12.setMinimumSize(QtCore.QSize(0, 400))
        self.CardWidget_12.setMaximumSize(QtCore.QSize(16777215, 400))
        self.CardWidget_12.setObjectName("CardWidget_12")
        self.StrongBodyLabel_6 = StrongBodyLabel(self.CardWidget_12)
        self.StrongBodyLabel_6.setGeometry(QtCore.QRect(10, 10, 111, 19))
        self.StrongBodyLabel_6.setObjectName("StrongBodyLabel_6")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.CardWidget_12)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 641, 73))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ImportManagedVersionSave = PushButton(self.horizontalLayoutWidget_2)
        self.ImportManagedVersionSave.setObjectName("ImportManagedVersionSave")
        self.horizontalLayout_2.addWidget(self.ImportManagedVersionSave)
        self.RefreshManagedVersionSaves = PushButton(self.horizontalLayoutWidget_2)
        self.RefreshManagedVersionSaves.setObjectName("RefreshManagedVersionSaves")
        self.horizontalLayout_2.addWidget(self.RefreshManagedVersionSaves)
        self.OpenManagedVersionSavesDir_2 = PushButton(self.horizontalLayoutWidget_2)
        self.OpenManagedVersionSavesDir_2.setObjectName("OpenManagedVersionSavesDir_2")
        self.horizontalLayout_2.addWidget(self.OpenManagedVersionSavesDir_2)
        self.JumpDownloadingSavesForManagedVersion = PushButton(self.horizontalLayoutWidget_2)
        self.JumpDownloadingSavesForManagedVersion.setObjectName("JumpDownloadingSavesForManagedVersion")
        self.horizontalLayout_2.addWidget(self.JumpDownloadingSavesForManagedVersion)
        self.SearchManagedVersionSaves = SearchLineEdit(self.horizontalLayoutWidget_2)
        self.SearchManagedVersionSaves.setObjectName("SearchManagedVersionSaves")
        self.horizontalLayout_2.addWidget(self.SearchManagedVersionSaves)
        self.ManagedVersionSavesView = ListWidget(self.CardWidget_12)
        self.ManagedVersionSavesView.setGeometry(QtCore.QRect(30, 120, 611, 261))
        self.ManagedVersionSavesView.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: white;\n"
"    border-radius: 10px;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.ManagedVersionSavesView.setObjectName("ManagedVersionSavesView")
        self.verticalLayout_4.addWidget(self.CardWidget_12)
        self.SmoothScrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.poper.addWidget(self.page_4)
        self.Navigation = NavigationInterface(LineMinecraftlauncher)
        self.Navigation.setGeometry(QtCore.QRect(10, 10, 48, 431))
        self.Navigation.setObjectName("Navigation")
        self.Background = QtWidgets.QLabel(LineMinecraftlauncher)
        self.Background.setGeometry(QtCore.QRect(0, 0, 851, 481))
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.Background.raise_()
        self.poper.raise_()
        self.Navigation.raise_()

        self.retranslateUi(LineMinecraftlauncher)
        self.poper.setCurrentIndex(5)
        self.PopUpAniStackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(LineMinecraftlauncher)

    def retranslateUi(self, LineMinecraftlauncher):
        _translate = QtCore.QCoreApplication.translate
        LineMinecraftlauncher.setWindowTitle(_translate("LineMinecraftlauncher", "Line Minecraft Launcher"))
        self.SubtitleLabel_3.setText(_translate("LineMinecraftlauncher", "Line Minecraft 启动器"))
        self.SubtitleLabel_2.setText(_translate("LineMinecraftlauncher", "启动"))
        self.CaptionLabel_2.setText(_translate("LineMinecraftlauncher", "账户"))
        self.Launch.setProperty("text_", _translate("LineMinecraftlauncher", "启动 {version}"))
        self.LoginTypeSwitcher.setText(_translate("LineMinecraftlauncher", "离线登录"))
        self.CaptionLabel_5.setText(_translate("LineMinecraftlauncher", "Minecraft路径"))
        self.ManageMinecraft.setText(_translate("LineMinecraftlauncher", "管理路径"))
        self.AddMinecraftDirectory.setText(_translate("LineMinecraftlauncher", "添加路径"))
        self.MemorySizeDisplay.setText(_translate("LineMinecraftlauncher", "Nah"))
        self.CaptionLabel.setText(_translate("LineMinecraftlauncher", "内存大小:"))
        self.AutoMemoryManagement.setText(_translate("LineMinecraftlauncher", "让程序决定我的内存大小"))
        self.SubtitleLabel.setText(_translate("LineMinecraftlauncher", "账户管理"))
        self.OfflinedLogin.setText(_translate("LineMinecraftlauncher", "离线登录"))
        self.MicrosoftLogin.setText(_translate("LineMinecraftlauncher", "微软登录"))
        self.LittleSkinLogin.setText(_translate("LineMinecraftlauncher", "LittleSkin"))
        self.ExtraLogin.setText(_translate("LineMinecraftlauncher", "外置登录"))
        self.StrongBodyLabel_4.setText(_translate("LineMinecraftlauncher", "用户名"))
        self.OfflinedUsernameEdit.setPlaceholderText(_translate("LineMinecraftlauncher", "不可包含除英文、下划线、数字以外的字符"))
        self.ConfirmOfflinedUsername.setText(_translate("LineMinecraftlauncher", "确定"))
        self.ClearOfflinedUsername.setText(_translate("LineMinecraftlauncher", "清除"))
        self.TitleLabel.setText(_translate("LineMinecraftlauncher", "注意！您正在进行微软登录"))
        self.BodyLabel_15.setText(_translate("LineMinecraftlauncher", "提示"))
        self.StrongBodyLabel_8.setText(_translate("LineMinecraftlauncher", "  我为什么会看到此页面？\n"
"因为您正在尝试使用微软账户登录Minecraft，请按照以下步骤完成授权"))
        self.CaptionLabel_3.setText(_translate("LineMinecraftlauncher", "1. 确保网络通畅，在必要时请自行启用网络代理服务，本启动器不提供任何此类服务"))
        self.CaptionLabel_4.setText(_translate("LineMinecraftlauncher", "2. 确保已经在官网购买了Minecraft Java游戏且已注册档案"))
        self.CaptionLabel_6.setText(_translate("LineMinecraftlauncher", "3. 确认后按下本页面右下角的按钮，届时启动器将打开一个新网页"))
        self.CaptionLabel_7.setText(_translate("LineMinecraftlauncher", "4. 登录您购买了Minecraft Java的微软账户"))
        self.CaptionLabel_8.setText(_translate("LineMinecraftlauncher", "5.在下一个页面，请允许LMC访问您的信息，否则登录将失败"))
        self.CaptionLabel_9.setText(_translate("LineMinecraftlauncher", "6.待到网页指示，您可以安全地关闭网页，请勿重复点击登录按钮，耐心等待完成"))
        self.ConfirmStartMicrosoftLogin.setText(_translate("LineMinecraftlauncher", "我已认真阅读上述内容，现在进行登录"))
        self.BuyMinecraft.setText(_translate("LineMinecraftlauncher", "购买游戏"))
        self.SubtitleLabel_4.setText(_translate("LineMinecraftlauncher", "终端"))
        self.SubtitleLabel_5.setText(_translate("LineMinecraftlauncher", "游戏下载与管理"))
        self.Download.setText(_translate("LineMinecraftlauncher", "下载"))
        self.CurseForgeModDownload.setText(_translate("LineMinecraftlauncher", "MOD"))
        self.BodyLabel_2.setText(_translate("LineMinecraftlauncher", "CurseForge"))
        self.CurseForgePackagesDownload.setText(_translate("LineMinecraftlauncher", "整合包"))
        self.SubtitleLabel_6.setText(_translate("LineMinecraftlauncher", "设置"))
        self.BodyLabel_7.setText(_translate("LineMinecraftlauncher", "下载源"))
        self.BodyLabel_12.setText(_translate("LineMinecraftlauncher", "语言设定"))
        self.BodyLabel_8.setText(_translate("LineMinecraftlauncher", "Java 选项"))
        self.BodyLabel_9.setText(_translate("LineMinecraftlauncher", "游戏 Java 选择策略"))
        self.AddJavaManually.setText(_translate("LineMinecraftlauncher", "手动添加"))
        self.BodyLabel_10.setText(_translate("LineMinecraftlauncher", "强制使用的 Java (仅当策略为强制时可用)"))
        self.SearchJava.setText(_translate("LineMinecraftlauncher", "搜索Java"))
        self.BodyLabel_11.setText(_translate("LineMinecraftlauncher", "启动器可见性"))
        self.BodyLabel_16.setText(_translate("LineMinecraftlauncher", "选择下载器"))
        self.BodyLabel_17.setText(_translate("LineMinecraftlauncher", "下载器并发数"))
        self.StrongBodyLabel_10.setText(_translate("LineMinecraftlauncher", "Nah Concurrents"))
        self.StrongBodyLabel_11.setText(_translate("LineMinecraftlauncher", "警告！下载并发数不是越多越好，不匹配的并发数会导致下载效率变低"))
        self.BodyLabel_18.setText(_translate("LineMinecraftlauncher", "启动器背景"))
        self.ShowOldVersions.setText(_translate("LineMinecraftlauncher", "显示远古"))
        self.ShowSnapshotVersions.setText(_translate("LineMinecraftlauncher", "显示快照"))
        self.RefreshVersions.setText(_translate("LineMinecraftlauncher", "刷新"))
        self.SearchInVersionsView.setPlaceholderText(_translate("LineMinecraftlauncher", "搜索一个版本"))
        self.SubtitleLabel_10.setText(_translate("LineMinecraftlauncher", "下载详情"))
        self.ConfirmDownload.setText(_translate("LineMinecraftlauncher", "确认"))
        self.ClearOption.setText(_translate("LineMinecraftlauncher", "清空"))
        self.ReturnPreviousStep.setText(_translate("LineMinecraftlauncher", "返回"))
        self.BodyLabel_4.setText(_translate("LineMinecraftlauncher", "名称"))
        self.IsNameAvailable.setText(_translate("LineMinecraftlauncher", "可用"))
        self.BodyLabel_3.setText(_translate("LineMinecraftlauncher", "Forge"))
        self.BodyLabel_5.setText(_translate("LineMinecraftlauncher", "Optifine"))
        self.BodyLabel_6.setText(_translate("LineMinecraftlauncher", "Fabric"))
        self.BodyLabel_13.setText(_translate("LineMinecraftlauncher", "Optifabric"))
        self.BodyLabel_14.setText(_translate("LineMinecraftlauncher", "Fabric API"))
        self.SubtitleLabel_11.setText(_translate("LineMinecraftlauncher", "Minecraft 路径管理"))
        self.StrongBodyLabel_9.setText(_translate("LineMinecraftlauncher", "右击选中的项目来管理"))
        self.SubtitleLabel_12.setText(_translate("LineMinecraftlauncher", "版本详情"))
        self.StrongBodyLabel.setText(_translate("LineMinecraftlauncher", "版本名称"))
        self.ConfirmNewManagedVersionID.setText(_translate("LineMinecraftlauncher", "确定"))
        self.CancelNewManagedVersionID.setText(_translate("LineMinecraftlauncher", "取消"))
        self.IsNewManagedVersionIDAvail.setText(_translate("LineMinecraftlauncher", "可用"))
        self.StrongBodyLabel_2.setText(_translate("LineMinecraftlauncher", "检查单"))
        self.StrongBodyLabel_7.setText(_translate("LineMinecraftlauncher", "以下显示了已附加安装的内容及其版本"))
        self.StrongBodyLabel_3.setText(_translate("LineMinecraftlauncher", "快捷方式"))
        self.OpenManagedVersionDir.setText(_translate("LineMinecraftlauncher", "打开版本目录"))
        self.OpenManagedVersionSavesDir.setText(_translate("LineMinecraftlauncher", "打开存档目录"))
        self.GenerateManagedVersionLaunchingScript.setText(_translate("LineMinecraftlauncher", "生成启动脚本"))
        self.CleanManagedVersionDir.setText(_translate("LineMinecraftlauncher", "清理目录"))
        self.DelManagedVersion.setText(_translate("LineMinecraftlauncher", "彻底删除此版本"))
        self.StrongBodyLabel_5.setText(_translate("LineMinecraftlauncher", "Mod管理"))
        self.ImportManagedVersionMod.setText(_translate("LineMinecraftlauncher", "导入"))
        self.RefreshManagedVersionMod.setText(_translate("LineMinecraftlauncher", "刷新"))
        self.OpenManagedVersionModDir.setText(_translate("LineMinecraftlauncher", "打开文件夹"))
        self.JumpDownloadingModForManagedVersion.setText(_translate("LineMinecraftlauncher", "下载"))
        self.SearchManagedVersionMod.setText(_translate("LineMinecraftlauncher", "搜索"))
        self.StrongBodyLabel_6.setText(_translate("LineMinecraftlauncher", "世界管理"))
        self.ImportManagedVersionSave.setText(_translate("LineMinecraftlauncher", "导入"))
        self.RefreshManagedVersionSaves.setText(_translate("LineMinecraftlauncher", "刷新"))
        self.OpenManagedVersionSavesDir_2.setText(_translate("LineMinecraftlauncher", "打开文件夹"))
        self.JumpDownloadingSavesForManagedVersion.setText(_translate("LineMinecraftlauncher", "下载"))
        self.SearchManagedVersionSaves.setText(_translate("LineMinecraftlauncher", "搜索"))
from qfluentwidgets import BodyLabel, CaptionLabel, CardWidget, CheckBox, ComboBox, EditableComboBox, HorizontalSeparator, IconWidget, LineEdit, ListWidget, NavigationInterface, PopUpAniStackedWidget, PrimarySplitPushButton, PushButton, SearchLineEdit, SimpleCardWidget, Slider, SmoothScrollArea, StrongBodyLabel, SubtitleLabel, TitleLabel, ToggleButton
import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import Icons_rc
