# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Coding\LineMinecraftLauncherProject\Refactor\Line\Interface\Interface\DownloadingInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DownloadingInfo(object):
    def setupUi(self, DownloadingInfo):
        DownloadingInfo.setObjectName("DownloadingInfo")
        DownloadingInfo.resize(639, 341)
        self.HeaderCardWidget = HeaderCardWidget(DownloadingInfo)
        self.HeaderCardWidget.setGeometry(QtCore.QRect(0, 0, 641, 341))
        self.HeaderCardWidget.setObjectName("HeaderCardWidget")
        self.SimpleCardWidget = SimpleCardWidget(self.HeaderCardWidget)
        self.SimpleCardWidget.setGeometry(QtCore.QRect(10, 60, 611, 81))
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.StrongBodyLabel = StrongBodyLabel(self.SimpleCardWidget)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(10, 10, 111, 19))
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.DownloadingProgress = ProgressBar(self.SimpleCardWidget)
        self.DownloadingProgress.setGeometry(QtCore.QRect(10, 40, 221, 4))
        self.DownloadingProgress.setObjectName("DownloadingProgress")
        self.DownloadingPercent = StrongBodyLabel(self.SimpleCardWidget)
        self.DownloadingPercent.setGeometry(QtCore.QRect(240, 30, 111, 19))
        self.DownloadingPercent.setObjectName("DownloadingPercent")
        self.StartAndPause = ToggleButton(self.SimpleCardWidget)
        self.StartAndPause.setGeometry(QtCore.QRect(480, 40, 112, 32))
        self.StartAndPause.setObjectName("StartAndPause")
        self.Shutdown = PushButton(self.SimpleCardWidget)
        self.Shutdown.setGeometry(QtCore.QRect(370, 40, 102, 32))
        self.Shutdown.setObjectName("Shutdown")
        self.SimpleCardWidget_2 = SimpleCardWidget(self.HeaderCardWidget)
        self.SimpleCardWidget_2.setGeometry(QtCore.QRect(10, 150, 611, 181))
        self.SimpleCardWidget_2.setObjectName("SimpleCardWidget_2")
        self.StrongBodyLabel_2 = StrongBodyLabel(self.SimpleCardWidget_2)
        self.StrongBodyLabel_2.setGeometry(QtCore.QRect(10, 10, 111, 19))
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.CheckList = ListWidget(self.SimpleCardWidget_2)
        self.CheckList.setGeometry(QtCore.QRect(20, 40, 571, 111))
        self.CheckList.setObjectName("CheckList")

        self.retranslateUi(DownloadingInfo)
        QtCore.QMetaObject.connectSlotsByName(DownloadingInfo)

    def retranslateUi(self, DownloadingInfo):
        _translate = QtCore.QCoreApplication.translate
        DownloadingInfo.setWindowTitle(_translate("DownloadingInfo", "Form"))
        self.HeaderCardWidget.setTitle(_translate("DownloadingInfo", "正在下载"))
        self.StrongBodyLabel.setText(_translate("DownloadingInfo", "总进度"))
        self.DownloadingPercent.setText(_translate("DownloadingInfo", "Nah%"))
        self.StartAndPause.setText(_translate("DownloadingInfo", "暂停"))
        self.Shutdown.setText(_translate("DownloadingInfo", "终止"))
        self.StrongBodyLabel_2.setText(_translate("DownloadingInfo", "检查单"))


from qfluentwidgets import (
    HeaderCardWidget,
    ListWidget,
    ProgressBar,
    PushButton,
    SimpleCardWidget,
    StrongBodyLabel,
    ToggleButton,
)
